andes/andes-test-integracion

cypress/integration/matriculaciones/registrarProfesional.spec.js, cypress/integration/matriculaciones/testRegistrarProfesional-jsons
Se realiza la prueba de crear un nuevo profesional en matriculaciones.
=> Matriculaciones - Carga de un nuevo Profesional

cypress/integration/auditoria/auditoria.spec.js
Se prueban las US
https://pm.andes.gob.ar/projects/mpi/work_packages/362/activity
https://pm.andes.gob.ar/projects/mpi/work_packages/359/activity
=> Vinculación de pacientes

.gitignore, config.private.js.example, cypress.env.json, cypress/integration/core/huds/huds.spec.js, cypress/integration/util.js
andes/app#1152
1. Creación de funciones utils reutilizables para tests de permisos en general y permisos de acceso en particular. 
2. Parametrización de credenciales, objectIds y rutas en cypress.env 
3. Implementación de test de permiso de acceso para buscador de pacientes en HUDS utilizando las funciones mencionadas en punto 1
=> Permisos Huds & funciones utils para validación de permisos

cypress/integration/apps/rup/huds.spec.js
Prueba de corrección del issue https://github.com/andes/app/issues/792
app: issue#1111
api: master
=> Test corrección issue #792 (Filtros en la HUDS de un paciente)

.gitignore, cypress/integration/apps/citas/agenda/agendaNormal.spec.js
Prueba corrección issue https://github.com/andes/app/issues/1237
app: issue#1237
api: issue#1237
=> Test corrección issue #1237 (Clonación de agendas)

cypress/fixtures/apps/citas/turnos/agendaTurnoDia.json, cypress/fixtures/solicitudes/agendaProfesional.json, cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/integration/core/mpi/mpi.spec.js, cypress/support/commands.js
Se eliminaron las búsquedas con ng-reflect reemplazándolos con labels
=> Quita ng-reflect

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/mapaEspacioFisico/espaciosFisicos.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/rup/prestaciones.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/integration/core/tm/profesional/profesional.spec.js, cypress/support/commands.js, scripts/registrarProfesional.spec.js
- Se agregan dos commands para simplificar el uso de plex-select en los tests
=> Agrega commands para plex-select

cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js
A la prueba de iniciar prestación fuera de agenda se le agregó la verificación de que se haya validado correctamente
=> RUP - Validación rup

cypress/fixtures/agenda-rup.json, cypress/fixtures/paciente-sobreturno.json, cypress/fixtures/paciente-turno.json, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js, cypress/support/commands.js
Se crearon las pruebas de Iniciar y validar prestación en turno y sobreturno
Ambas son de Consulta de medicina general y se cargan con una agenda que se crea para el momento desde el fixture
Necesita agregar 2 pacientes a la coleccion `paciente`
```
{
"_id" : ObjectId("5d790c8b59530a13545f8394"),
"claveBlocking" : [ 
"TRNPZN", 
"TRN", 
"PZNT", 
"3960463", 
"396"
],
"entidadesValidadoras" : [ 
""
],
"documento" : "31549268",
"cuil" : null,
"activo" : true,
"estado" : "temporal",
"nombre" : "PACIENTE",
"apellido" : "TURNO",
"alias" : "",
"contacto" : [ 
{
"activo" : true,
"_id" : ObjectId("5d790c8b59530a13545f8395"),
"tipo" : "celular",
"valor" : "",
"ranking" : 0,
"ultimaActualizacion" : ISODate("2019-09-11T12:01:35.339-03:00")
}
],
"sexo" : "masculino",
"genero" : "masculino", …
```
=> RUP - Prestación en agenda

cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js, cypress/support/http.js, cypress/support/index.js
* Modifica orden de ejecución de clicks y wait
* Agrega comandos para comunicarse con la api (GET, POST, PATCH, PUT)
=> fix(turnos): Soluciona ejecución de test de punto de Inicio de Turnos

.gitignore, cypress/fixtures/apps/solicitud/paciente-nueva-solicitud.json, cypress/fixtures/paciente-normal.json, cypress/integration/apps/solicitud/nuevaSolicitud.spec.js, cypress/support/plex.js, cypress/support/seed.js, results/cypress-report.xml
=> feat (top): agrega casos nueva solicitud

cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js
Agrega casos de test para nueva solicitud de entrada
=> feat(top): Agrega casos para nueva solicitud de entrada

cypress/fixtures/agenda-turno-paciente.json, cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/support/darTurno.js, cypress/support/seed.js
1. Se agregó test para editar datos de contacto
2. Se agregó test para dar y quitar asistencia de turno
3. Se agregó test para liberar turno
- [] Si
=> feat(CITAS): Se agregaron tests en punto de inicio de citas

cypress/fixtures/apps/citas/agendas/agenda-historial.json, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/support/seed.js
Completar los casos de test del punto de inicio del módulo de Citas
1. Se realizó caso de test en el tab de "Historial"
2. Se realizó caso de test en el tab de "Carpetas"
3. Se agrega un nuevo fixture "agenda-historial" en el cuál ya viene con el paciente cargado para que aparezca en el historial del mismo.
=> feat(CITAS): Punto de inicio de citas

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js, cypress/integration/apps/rup/prestaciones.spec.js, cypress/support/plex.js
Armar en el archivo plex el command del toast para una utilización más eficiente y modificar el llamado del toast en los archivos que contengan el código anterior.
=> feat(PLEX): Se agrega toast

cypress/integration/apps/gestor-usuarios/perfiles.spec.js, cypress/support/plex.js
Edición de prestaciones de un perfil creado
1. Agrega variable en plexSelectType para permitir elegir el primer element
_(Nota: queda pendiente realizar el cambio con el plex accordion)_
=> test(perfiles): tests de edición de prestaciones

cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/plugins/seed-agenda.js
Actualizar el punto de inicio de citas con lo nuevo para crear agendas y pacientes
1. Se agregó en el archivo seed.agenda.js **diagnostico -> codificaciones** para el momento en cuando se crea una agenda
2. Se modifico el test de carpetas
3. Se modifico el test de historial para que tenga coherencia con lo nuevo
4.
=> fix(CITAS): Actualización en el punto de inicio de citas

cypress/integration/apps/citas/turnos/turnos.spec.js
Cambiar los cy.selectWrite por plex.select . Caso de test en jenkins #65 
1. Se cambiaron todos los cy.selectWrite por plex.select
2. Se agregó en el archivo turnos.spec.js plex.int
3. Se agregó en el archivo turnos.spec.js plex.text
4. Se agregó en el archivo turnos.spec.js plex.bool
5. Se agregó en el archivo turnos.spec.js plex.button
6. Se agregó en el archivo turnos.spec.js plex.buttonIcon
7. Se agregó en el archivo turnos.spec.js plex.DateTime
8. Se agregó en el archivo turnos.spec.js plex.phone
9. cy.task('database:create:paciente')
10. cy.task('database:seed:agenda')
=> refactor(TURNOS): cambios varios

cypress/integration/core/tm/profesional/profesional.spec.js
Arreglamos con @JSantarelli  el test de profesional!
=> fix(profesional): fix formato documento

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/mapaEspacioFisico/espaciosFisicos.spec.js, cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/rup/ejecucion.spec.js
Se cambia selectOption por plexSelect y se hace un cambio en el historial para que no busque en ningun eq() especifico
=> Refactor: reemplaza selectOption por plexSelect 

cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
Faltaba un wait de GET de paciente, por un asyncronismo en MPI.
=> fix(mpi): add missing wait

cypress/integration/apps/rup/ejecucion.spec.js
Analizar los tests de rup que fallaban y corregirlos.
1.  Se arreglaron los tests de rup - fuera de agenda, sobreturno y turno
2. 
3.
=> fix(rup): stub de huds en ejecución de RUP

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
=> fix(citas): reasignar turno

cypress/integration/apps/rup/punto-inicio.spec.js
1.  Su suman a los casos de test los wait para evitar que fallen
=> RUP: refactor de tests de punto de inicio

cypress/integration/apps/rup/ejecucion.spec.js
Verificar error
Timed out retrying: Expected to find content: 'Validar consulta de medicina general' within the element: [ <plex-button.collapse-card>, 4 more... ] but never did.
1. Elimina force
2. 
3.
=> fix(rup): se quita force de button

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
Cambia route de getAgendas
1. Cambia route de getAgendas
2. 
3.
=> fix(agendas): cambia la ruta de get

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
Controlar los wait que no dejaban reasignar los turnos de las agendas
1. 
2. 
3.
=> Fix(AGENDA): cambios en reasignar turnos

cypress/integration/apps/rup/ejecucion.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js
actualiza tests punto inicio otras agendas
=> fix(punto inicio rup): actualiza tests punto inicio otras agendas

cypress/fixtures/apps/rup/nino-sano.json, cypress/integration/apps/rup/nino-sano.spec.js, cypress/support/plex.js
=> feat(rup): agrega consulta nino sano

cypress/integration/apps/rup/ejecucion.spec.js
=> fix(rup): botón default en buscador

cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/integration/core/mpi/mpi-registro-sin-dni.spec.js
=> fix(varios): quita onlys

cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
1. Se agrego test de similitud de un paciente con uno validado del 81%
2. Se agrego test de similitud de un paciente con uno validado del 96%
3. Se modificaron test ya creados, acorde a los cambios en el proceso de similitud
=> MPI: Se modifican los tests de similitud de los pacientes

cypress/fixtures/mpi/paciente-validado2.json, cypress/fixtures/mpi/paciente-validado3.json, cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
1. Se agrego test de similitud de un paciente con uno validado del 83%
2. Se agrego test de similitud de un paciente con uno validado del 95%
3. Se modificaron test ya creados, acorde a los cambios en el proceso de similitud
=> MPI: Test de similitud de pacientes

cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js
1. Control luego de seleccionar agenda del dia en el calendario para dar un turno
2. Control luego de seleccionar una agenda para dar un turno autocitado
=> fix: arreglo de errores en test citas y solicitudes

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
1. Control antes de cargar prestaciones de agenda
2. Control luego de cargar profesional y que verifique si tiene alguna agenda con la misma prestacion en ese horario.
3. Control luego de cargar el espacio físico y que verifique si tiene alguna agenda con la misma prestacion en ese horario.
=> fix(CITAS): Planificación de agendas

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js
Error en test para la clonación de agendas no nominalizadas y en el test de visualizacion de boton iniciar prestacion ya que aparecía modal nuevo tras actualización en master.
1. Se agregan controles para la carga de agendas tanto en el gestor de agendas como en Rup
2. Se agregar plexBool y plexButton para cuando aparezca el modal
=> fix: Clonación de genda no nominalizada y visualizacion rup

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/rup/punto-inicio.spec.js
Error en test de visualización "iniciar prestacion" y al guardar y clonar agenda del dia con un solo bloque
=> fix(CITAS-RUP): Arreglo de test en planificacion agenda y punto inicio de RUP

cypress/integration/apps/rup/internacion/epicrisis.spec.js, cypress/support/plex.js
Tests de punto de inicio de epicrisis
1.  Tests de punto de inicio de epicrisis 
2. Agrega al comando 'plexDatetime' un flag opcional para ignorar el tipeo de 'enter' despues de tipear el valor
=> Internaciones: tests de punto de inicio de epicrisis

cypress/integration/core/mpi/busqueda.spec.js, cypress/integration/core/mpi/mpi-registro-bebe.spec.js, cypress/integration/core/mpi/mpi-registro-con-dni.spec.js, cypress/integration/core/mpi/mpi-registro-extranjero.spec.js, cypress/integration/core/mpi/mpi-registro-sin-dni.spec.js
Agregar mas controles en las respuestas que devuelve la api
1. En cada test se agregaron verificaciones de los datos de los pacientes que devuelve la api
- [] Si
=> MPI: se agregan respuestas de la api

cypress/integration/core/tm/profesional/profesional.spec.js
Agregar mas controles en las respuestas que devuelve la api
1. En cada test se agregaron verificaciones de los datos del profesional que devuelve la api
- [] Si
=> Profesional: se agregan respuestas de la api

cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/support/commands.js
1..  Actualiza los test correspondientes para el nuevo token.
=> feat(login): new login route

cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/plugins/seed-prestaciones.js
=> feat(rup): agrega test con solicitud

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
Agrega tests al buscador de turnos y prestaciones
1. 
2. 
3.
=> feat(buscador):  Buscador de Turnos y Prestaciones

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
Tests en buscador de prestaciones y turnos
1. Cambia la función goto
2. 
3.
=> fix(buscador): actualiza tests del buscador de prestaciones

cypress/integration/apps/solicitud/solicitudes.spec.js
1. Test para crear solicitud de entrada y verificar filtros
2. Test para crear solicitud de entrada y auditarla
- [] Si
=> Solicitudes: Se agregan test

cypress/integration/apps/solicitud/solicitudes.spec.js
correccion en test dar turno autocitado
1. Elimina get extra
2. 
3. 
- [] Si
- [] No
=> fix(turno autocitado): corrige error al comparar con null

cypress/integration/apps/citas/turnos/punto_inicio.spec.js
Adaptar test a incorporacion de domicilio legal de paciente en punto inicio de CITAS
- [] Si
=> CITAS - domicilio legal en informacion de paciente

.jenkins/docker-build.jenkins, cypress/integration/monitoreo/conceptos_turneables.spec.js, cypress/integration/monitoreo/login.spec.js, cypress/integration/monitoreo/webhook.spec.js
Casos de Test para módulo Monitoreo: Login Conceptos Turneables y Webhook
Login
1. Login complete: login exitoso de un usuario.
2. Login failed: login incorrecto de un usuario. 
Conceptos Turneables:
1. Alta de un concepto turneable
2. Editar un concepto turneable
3. Eliminar un concepto turneable
Webhook:
1. Alta de un webhook
2. Editar un webhook
3. Eliminar un webhook
=> Test monitoreo

cypress/integration/apps/rup/ejecucion.spec.js
Eliminar el "Seleccionar paciente" al momento de querer iniciar prestación fuera de agenda
1. Se eliminó el "Seleccionar paciente"
=> fix(RUP):  iniciar prestación fuera de agenda con nota privada

cypress/integration/apps/rup/internacion/epicrisis.spec.js
corrige test de epicrisis para PR https://github.com/andes/app/pull/1613
=> fix(internacion): fix crear epicrisis

cypress/integration/apps/citas/turnos/dar_turno.spec.js
Al momento de crear un turno controlar que se guarden correctamente en BD
1. Se agrega test que verifica que se guarde la tanto la fecha y la hora de dacion del turno como el usuario que lo dio.
=> CITAS: Test que verifica fecha/hora y usuario dacion de turno

cypress/integration/apps/rup/odontograma/odontograma.spec.js
Arreglar test de odontograma que fallaban por falta de una semanticTag
1. Se agregó semanticTag "fármaco de uso clínico"
2. 
3.
=> fix(RUP): agrega semanticTag

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
1. Se cambio de lugar el wait de clonar, para que este después de confirmar la clonación y no antes
2. 
3.
=> fix(CITAS): Guardar y clonar agenda del día con un solo bloque

cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/support/plex.js
Al no esperar los wait correspondientes el test de "nueva solicitud, asignación a profesional y control de historial" siempre se hacia un retry para que pueda pasar correctamente.
1. Se agregaron los wait en el test nueva solicitud, asignación a profesional y control de historial
2. Se agrego en plex un command para el mensaje que salia al momento de crear una solicitud
3. Se agrego el command en todos los test correspondientes
**TOP: Nueva Solicitud de Entrada**
**TOP: Nueva Solicitud de Salida**
=> Fix(TOP): Mejora al crear nueva solicitud

cypress/fixtures/mpi/paciente-validado.json, cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
1. Controlar que al "validar un paciente" dicha direccion de renaper se guarde en la posicion [1] del array de direcciones del paciente
2.Controlar que al editar direccion del paciente se edite la direccion que esta ubicada en la posicion [0] del array de direcciones
- [] Si
=> MPI - Direccion real/legal de un paciente

cypress/integration/monitoreo/activaciones-app-mobile.spec.js, cypress/plugins/index.js, cypress/plugins/seed-paciente-app.js
Se realizaron los test para Monitoreo Activaciones de la App Mobile.
* Los casos de test son:
1. Buscar paciente por documento y verificar que no existe.
2. Buscar paciente por documento que exista y verificar que devuelva datos.
3. buscar paciente por documento que exista, seleccionarlo del listado y verificar que cargue sus datos en el sidebar.
4. Buscar paciente por documento que exista, seleccionarlo del listado y verificar que cargue su historial.
* Se creó la task para crear paciente-app.
=> Monitoreo - Monitoreo Activaciones App Mobile

cypress/integration/apps/rup/elementos-rup/atomo-select.spec.js
Agrega test para los átomos de seleccion.
https://github.com/andes/app/pull/1572
=> feat(elemento-rup): testing de selects parametrizables

cypress/integration/apps/auditoria/auditoria.spec.js
Agrego 3 pruebas de vincular pacientes sin documento
1. Vincular paciente validado con uno temporal (sin documento)
2. Vincular paciente temporal con documento con uno temporal sin documento
3. Vincular dos pacientes temporales sin documento
- [] Si
=> MPI - Auditoría pacientes sin documentos

cypress/integration/core/auth/login.spec.js
Se agregar casos de tests para disclaimers al iniciar sesión
1. Test para verificar que figure el disclaimer y aceptarlo
2. Test para verificar que figure el disclaimer y rechazarlo
=> PRIVACIDAD: Tests de disclaimer

cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/plugins/seed-agenda.js
Agregar test de liberación de turno de solicitud
1. Agrega test de liberación de turno de solicitud
=> TOP: agrega test de liberación de turno de solicitud

cypress/integration/core/auth/select-organizacion.spec.js
Fallaba el test de cambiar organización al momento de verificar si había cambiado efectivamente de efector
1. Se agrego un wait de organizaciones
2. Se agrego un wait de disclaimer
=> fix(AUTH): cambiar de organizacion

DOCUMENTACION.md, README.md, package.json
1. goto
2. task database:seed:agenda
3. route
4. task database:seed:paciente y database:create:paciente
5. login
=> doc(goto): documenta el uso de goto

cypress/integration/apps/gestor-usuarios/perfiles.spec.js, cypress/integration/apps/gestor-usuarios/usuarios.spec.js, cypress/plugins/data/gestor-usuarios/perfil-default.json, cypress/plugins/data/gestor-usuarios/usuario-default.json, cypress/plugins/index.js, cypress/plugins/seed-gestor-usuarios.js, cypress/support/gestorUsuario.js, cypress/support/index.js
Se agregaron 3 pruebas a la parte de gestión de usuarios. 2 corresponden a perfiles y una a los usuarios. Para estas pruebas se tuvo que agregar los seed para crear perfiles y usuarios utilizando el `cy.task()`
1. Crear nuevo perfil con diferentes niveles de permisos (agenda:*, campana:publicar, etc)
2. Crear un perfil y ver que no se cambien los permisos de otro perfil que ya existía
3. Asignar un perfil a un usuario
=> Permisos - Perfiles y usuarios

cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
Falla en test de 'editar direccion de un paciente existente y agregarle una relación' al querer seleccionar una relacion de una paciente.
1. Se agrego un force true
2. 
3.
=> fix(MPI): Agrega force:true cuando selecciona un relación

cypress/integration/apps/rup/elementos-rup/atomo-select.spec.js, cypress/integration/apps/rup/elementos-rup/seccionado.spec.js, cypress/plugins/seed-elementos-rup.js, cypress/support/index.js, cypress/support/plex.js, cypress/support/rup.js
=> feat(elemento-rup): agrega test de secciones rup

cypress/integration/apps/rup/ejecucion.spec.js
Arreglar rutas de snomed para funcionar correr tests en branches
https://github.com/andes/api/tree/RUP-15
https://github.com/andes/app/tree/RUP-15
1. RUP: agrega método GET a rutas snomed
- [] Si
=> RUP: agrega método GET a rutas snomed

cypress/integration/apps/rup/ejecucion.spec.js
Fix para test de nota privada y nueva funcionalidad
1. Se corrige el test de nota privada.
2. Se completa el test luego de que la funcionalidad subio a master(https://github.com/andes/andes-test-integracion/pull/115) 
- [] Si
=> RUP:fix nota privada

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_dos_prestaciones.spec.js
Test para https://github.com/andes/app/pull/1641
1. Test para https://github.com/andes/app/pull/1641
2. 
3. 
- [] Si
=> AGENDAS: Actualización test 2 prestaciones

cypress/integration/apps/rup/internacion/camas/camas.spec.js, cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js
Dado que en la app se actualizó la expresion de las especialidades se necesita actualizar los tests para que se correspondan con la nueva expresion.
1. Actualiza los tests para que se correspondan con la nueva expresion de especialidades
2. 
3.
=> INTERNACION - Actualliza los tests de internacion que usan especialidades

cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/rup/ejecucion.spec.js, cypress/integration/apps/rup/elementos-rup/atomo-select.spec.js, cypress/integration/apps/rup/elementos-rup/seccionado.spec.js, cypress/integration/apps/rup/nino-sano.spec.js, cypress/integration/apps/rup/odontograma/odontograma.spec.js, cypress/integration/core/auth/select-organizacion.spec.js, cypress/integration/core/tm/profesional/profesional.spec.js
Que los tests funcionen con esta versión: https://github.com/andes/app/pull/1624
1. Se actualizaron selectores de badge
2. Se corrigieron algunos selectores que fallaban, más notablemente varios botones con icono que hora son plex-button.
=> fix(plex-badge): Se hicieron actualizaciones en selectores "badge" y relacionados

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js
mantenimiento de test
1. Actualiza click a nuevo boton de suspension (plexButton)
2. fix en tet de nueva entrada de solicitud
- [] Si
=> Test: mantenimiento de test

cypress/integration/core/mpi/mpi-registro-con-dni.spec.js, cypress/integration/core/mpi/mpi-registro-de-paciente-similares.spec.js
Corregir algunos casos de test que fallaban recurrentemente.
1. Se corrigen aserciones (match para chequear similitud de pacientes) y elementos no encontrados que lanzaban error.
- [] Si
=> MPI - Fix de varios casos

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js, cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/support/time.js
Modificar test que fallan a fin de mes - _**REPORTE 595**_
**_Se hizo una prueba en jenkins para corroborar que los test sigan funcionando correctamente cuando no es fin de mes ( REPORTE 639 de jenkins)_**
Se modificaron los siguientes test
1. **Buscador de turnos y prestaciones**
- Listar turnos con filtro de fechas
- Listar turnos con filtros de fecha y tipo de prestación
- Listar turnos con filtros de fecha y equipo de salud logueado
2. **CITAS - Planificar agendas**
- Suspender turno de agenda publicada
3. **Planificación de agendas**
- Guardar y clonar agenda del día con un solo bloque
4. **CITAS - Punto de Inicio**
- Buscar agenda por prestacion(2 resultados)
- Buscar agenda por profesional (1 resultado)
- Dar turno programado con filtros - paciente validado
- Dar turno programado …
=> Fix - Casos test a fin de mes

cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js, cypress/integration/apps/rup/internacion/mapa-camas/filtros-camas.spec.js, cypress/plugins/seed-internacion.js
La app agregó la funcionalidad para poder filtrar las camas por sectores superiores entonces se necesita testear dicha funcionalidad.
1. Agrega tests para filtrar por sectores superiores
2. Modifica el seed-internacion para que las camas almacenen el arbol de sectores.
3.
=> INTERNACION - Agrega test para filtro de sectores superiores

cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js
Retirar getPrestaciones al momento de filtrar por prestación destino ya que se cargan todas al principio
1. Se cambio plexSelectAsync por plexSelectType
2. Se ordeno código general
3.
=> fix(TOP): filtro de prestación destino

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
Modificación en test por cambios en el buscador de turnos y prestaciones
1. Se modifican la cantidad de resultados obtenidos en los test dados los cambios realizados en la app https://github.com/andes/app/pull/1673
- [] Si
Correr en rama https://github.com/andes/app/pull/1673
=> MISC: Permisos en el buscador de turnos y prestaciones

cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
Se agregaron casos de test para la validación de paciente que ya existe como temporal.
1. se agregó test "validar con renaper nuevo paciente con ALTO % de matching contra un temporal ya existente"
2. se sagregó test "validar con renaper nuevo paciente con BAJO % de matching contra un temporal ya existente"
3. se corrigió uso plexSelec por plexSelecType al seleccionar sexo
=> MPI: validar paciente que existe como temporal

cypress/integration/apps/rup/internacion/mapa-camas/filtros-camas.spec.js
Que los usuarios puedan filtrar por numero de documento de paciente.
1. Agrega test que verifica el filtro por numero de documento.
2. 
3.
=> INTERNACION - Agrega test de filtro por numero de documento

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
Granuralizar la búsqueda del número de día para que solo busque ese valor dentro del calendario y no en toda la pantalla.
=> fix(CITAS): cambio en la búsqueda dia en calendarío

cypress/integration/monitoreo/novedades.spec.js, cypress/plugins/index.js, cypress/plugins/seed-modulo.js
Casos de test para módulo Novedades en App Monitoreo
https://github.com/andes/monitoreo-app/pull/14
* Casos de test
1. Registrar una Novedad y verificar que este en la lista
2. Se busca la primer novedad cargada como INACTIVA y se activa
3. Buscar una novedad por modulo
4. Buscar una novedad por titulo
* Módulo: task que crea módulos
1. Se crean módulos de acuerdo a los datos del módulo recibido.
2. Sino se reciben un módulo (o el módulo está incompleto) se crea un módulo (o se completa) con datos aleatorios.
- [] Si
=> Monitoreo: Test Registro Novedades

cypress/integration/apps/rup/internacion/epicrisis.spec.js
Eliminar codigo viejo de internacion 
https://github.com/andes/app/pull/1693
https://github.com/andes/api/pull/957
=> test(epicrisis): remueve wait a ruta

cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js
Fallan dos tests de internacion, el ingreso de estadistica y el ingreso de capa medica.
1.  Cambia el click en el botón "plus" para el ingreso ya que al tener dos botones "plus" a la vista pinchaba.
2. 
3.
=> INTERNACION - Arregla tests internacion que fallan con nuevos cambios

cypress/integration/apps/rup/elementos-rup/atomo-select.spec.js
Test SelectSnomedComponent Elemento TUP
1.  Agrega test para SelectSnomedComponent
https://github.com/andes/app/pull/1670
=> feat(elementos-rup): test select snomed concept

cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js
Que al asignar el turno busque correctamente la agenda si esamos cerca de fin de mes
1. Se cambio la condición de if
2. 
3.
=> fix(TOP): Cambia condición de IF

cypress/integration/monitoreo/modulos.spec.js
Tests para el nuevo gestor de módulos en monitoreo
1. Test para registro de nuevo módulo
2. Test para carga de módulo como INACTIVO y edición para activarlo
3. Test para búsqueda de un módulo por título
=> MONITOREO: tests para gestor de módulos

cypress/integration/apps/rup/elementos-rup/seccionado.spec.js, cypress/integration/apps/rup/internacion/epicrisis.spec.js
Cambio la forma de seleccionar el plex-html del átomo ObservacionesComponent
=> fix(rup): selector de ObservacionesComponent

cypress/integration/apps/gestor-usuarios/usuarios.spec.js
Agregar test para verificar fix Toggle "seleccionar todos" de Solicitudes
1. Se agrega test Seleccionar todas las prestaciones del modulo solicitud
- [] Si
Correr en rama de la APP https://github.com/andes/app/pull/1740
=> Gestor de usuarios: Seleccionar todas las prestaciones

cypress/fixtures/solicitudes/solicitud-auditoria.json, cypress/integration/apps/solicitud/referir-solicitud.spec.js, cypress/integration/apps/solicitud/remision-solicitud.spec.js
Test de remisión de solicitud
Correr con https://github.com/andes/app/tree/TOP11 y https://github.com/andes/api/tree/TOP11
1. Nuevo test de remisión de solicitud
2. Nuevo fixture de solicitud auditablel
- [] Si
=> TOP: Test de referir una solicitud

cypress/integration/core/auth/login.spec.js, cypress/integration/core/auth/select-organizacion.spec.js
Tests de disclaimers
1. Cambio en búsqueda de botón para que corran los tests con el nuevo modal del disclaimer
- [] Si
=> PRIVACIDAD: arreglo de tests de disclaimer para el nuevo modal

cypress/integration/monitoreo/novedades.spec.js
https://proyectos.andes.gob.ar/browse/MISC-76
=> TEST: independizar tests de novedades

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
Agregar condición de fin de mes para que se muevan al siguiente mes en el calendario al querer clonar una agenda
1. Se agregó condición en **"Clonar agenda con una institución asignada"**
2. Se agregó condición en **"Guardar y clonar agenda del día con un sólo bloque"**
3.
=> refactor(CITAS): agrega condición fin de mes

cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js
Se actualizó la nueva version de plex y el test "detalle cama" de internacion comenzó a fallar.
1. Se capturan los nuevos elementos ordenados en el html
2. 
3. 
- [] Si
=> INTERNACION - Arregla test detalle cama para la nueva version plex

cypress/integration/core/mpi/mpi-activar-app-mobile.spec.js
Se crean casos de test para la activación de app mobiles desde MPI
Casos de test desarrollados:
1. Activar app mobile, sin guardar el paciente (click en cancelar) y verificar que los datos persistan.
2. Activar app mobile en un paciente validado.
3. Intentar activar app mobile en un paciente con un correo que ya exista en otro paciente.
=> Casos de test activación app mobile desde mpi

cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js
Se quitaron varios GET redundantes en el punto de inicio RUP. Se quitan los wait en en los test.
=> Optimizacion reglas en punto inicio

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js
Arreglo test que fallan en el último reporte del día 13/07/2020 (#1082)
1. Se retiran route que trababan test
=> Fix - Arreglo test varios

cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js, cypress/integration/apps/rup/internacion/listado-internacion/romper-validar.spec.js, cypress/integration/apps/rup/internacion/utiles.js, cypress/plugins/seed-internacion.js
Agregar nuevos tests para la edición de un egreso, la validacion de una internacion y el hecho de romper la validacion.
1. Agrega tres tests nuevos para internacion: editar egreso, validar internacion y romper validacion
2. 
3. 
- [] Si
=> INTERNACION - Tests editar egreso, validar y romper validacion de internacion

cypress/integration/apps/gestor-usuarios/perfiles.spec.js
Cambiar el nombre del botón de ingreso a la seccion de perfiles, "VER PERFILES" -> "PERFILES"
=> PERFILES - Nuevo boton

cypress/integration/core/mpi/mpi-activar-app-mobile.spec.js
Se correge test en activación  de la App Mobile
1. Se corrige un test que fallaba y se agregan más controles.
=> Correge test en activacion  App Mobile

cypress/integration/apps/rup/elementos-rup/atomo-select.spec.js
Para testear RUP-22
1. atomo-select click primer chevron-down
- [] Si
- [] No
=> RUP: atomo-select click primer chevron-down

cypress/integration/apps/citas/agendas/gestor_agendas_listado.spec.js
Actualizar los test propuestos en el PR https://github.com/andes/andes-test-integracion/pull/42 
1. Se sacaron los fixture y se agregaron task de seed agendas
1. Visualizar detalle de agenda sin turnos asignados
2. Visualizar botonera de acciones para agenda planificada
3. Visualizar detalle de la configuración inicial del bloque
=> refactor(CITAS): actualización test de agendas

cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js, cypress/plugins/seed-agenda.js
Cambio el requerimiento __no visualiza agendas sin turnos__ por __visualiza agendas sin turnos__
=> feat(rup): cambia requerimiento en listado punto inicio

.jenkins/test.jenkins, cypress/plugins/index.js, cypress/plugins/seed-drop.js, cypress/plugins/seed-paciente.js, docker/docker-compose.yml, docker/docker-local.yml, package.json, scripts/prepare.js
Se elimina la conexión con elastic y se elimina de los contenedores
https://proyectos.andes.gob.ar/browse/MPI-184
1. Se elimina el uso de Elastic en los seed
2. Se elimina la conexión a Elastic y de los contenedores
=> MPI: Elimina elastic

package-lock.json, package.json
Agrega elastic para la parte de reportes
1. 
2. 
3. 
- [] Si
- [] No
=> fix(chore): add package elastic

cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js
Corrección de test para refactor de nuevas solicitudes
1. Se cambia la búsqueda del datetime de fecha de solicitud con el nuevo label
=> TOP: cambios en nuevaSolicitudEntrada y nuevaSolicitudSalida

cypress/integration/apps/auditoria/auditoria.spec.js, cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas.spec.js, cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js, cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_dos_prestaciones.spec.js, cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/rup/colonoscopia.spec.js, cypress/integration/apps/rup/ejecucion.spec.js, cypress/integration/apps/rup/internacion/camas/camas.spec.js, cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js, cypress/integration/apps/rup/nino-sano.spec.js, cypress/integration/apps/rup/odontograma/odontograma.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/integration/core/mpi/busqueda.spec.js, cypress/integration/core/mpi/mpi-activar-app-mobile.spec.js, cypress/integration/core/mpi/mpi-registro-bebe.spec.js, cypress/integration/core/mpi/mpi-registro-con-dni.spec.js, cypress/integration/core/mpi/mpi-registro-de-paciente-similares.spec.js, cypress/integration/core/mpi/mpi-registro-extranjero.spec.js, cypress/integration/core/mpi/mpi-registro-sin-dni.spec.js, cypress/integration/core/tm/profesional/profesional.spec.js, cypress/plugins/data/paciente/paciente-extranjero.json, cypress/plugins/seed-paciente.js, cypress/support/commands.js
Actualiza todos los tests de MPI debido al refactor del módulo.
1. Cambios en la distribución de los elementos en la búsqueda y edición de pacientes
2. Actualización de los componentes de plex
3. 
- [] Si
- [] No
=> refactor(mpi): cambios visuales de componentes

cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js
https://github.com/andes/app/pull/1819
1. Se saca getSolicitudes
2. 
3. 
- [] Si
- [] No
=> fix(TOP): getSolicitudes

cypress/integration/apps/solicitud/solicitudes.spec.js
1. force click paciente
2. 
3. 
- [] Si
- [] No
=> solicitudes: force click paciente

cypress/integration/core/mpi/mpi-activar-app-mobile.spec.js, cypress/integration/core/mpi/mpi-registro-bebe.spec.js, cypress/integration/core/mpi/mpi-registro-con-dni.spec.js, cypress/plugins/seed-paciente.js
Actualizar y ampliar test de pacientes similares.
Revisar  corregir test que fallan.
1. Se actualizaro test de paciente con dni para pacientes similares
2. Se agrega campo "scan" para recibirlo en los datos de un paciente (optativo) al seed de crear un paciente.
3. Se corrige y actualiza test de progenitor de un bebe usando el scanner en el buscador.
4. Se actualiza test de app-mobile
- [] Si
=> MPI: se actualizar y completan

cypress/integration/core/mpi/mpi-activar-app-mobile.spec.js, cypress/plugins/seed-paciente-app.js
Se actualiza seed de paciente-app
1. Se actualiza seed de paciente-app
2. Se actualiza y corrige test app mobile
- [] Si
=> MPI: se actualiza  seed paciente-app

cypress/fixtures/paciente-fallecido.json, cypress/integration/core/mpi/busqueda.spec.js
https://proyectos.andes.gob.ar/browse/MPI-193
https://proyectos.andes.gob.ar/browse/MPI-196
1. Se agrega busqueda de paciente con fecha de fallecimiento, en mpi
- [] Si
=> MPI - busqueda de paciente fallecido

cypress/integration/apps/pantallas/pantallas.spec.js
1. Se agregó un last al plexButtonIcon
=> fix(TURNERO): arreglo en crear nueva pantalla para turnero y editarla

cypress/integration/apps/rup/internacion/utiles.js
Ante la separación de permisos para crear y editar cama, es necesario agregar explícitamente el permiso para poder editar.
1. Agrega permiso a los usuarios creados en los tests de internacion para que puedan editar una cama.
2. 
3. 
- [] Si
=> INTERNACION - Agrega nuevo permiso para editar cama

cypress/integration/apps/pantallas/pantallas.spec.js
Agregar force true en select de espacios fisicos
=> fix(TURNERO): force true en crear nueva pantalla para turnero y editarla 

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas.spec.js
1. Se agrega una verificación para ver si cambio correctamente de pantalla
2. Se agregan expect para verificar status y el dni
=> fix(CITAS): revision de agendas

DOCUMENTACION.md, cypress/support/commands.js
En función login, si no hay parámetro de id de organización, toma por defecto id de castro en lugar de primer resultado de GET de organizaciones.
https://proyectos.andes.gob.ar/browse/MISC-79
- [] Si
- [] No
=> Log In: si no especifica id de organzacion, x defecto HPN

cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js, cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js, cypress/plugins/seed-internacion.js, scripts/seeder.js
=> fix(mapa-camas): varios errores en los test

cypress/plugins/seed-prestaciones.js
Agrega inicio de prestacion al seed
1. 
2. 
3.
=> feat(rup): add inicio prestacion

config.private.js.example, cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js, cypress/integration/apps/rup/internacion/medica/egresos.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/integration/core/mpi/mpi-registro-sin-dni.spec.js, cypress/integration/monitoreo/novedades.spec.js, cypress/plugins/data/internacion/maquina-estados-default.json, cypress/support/plex.js
=> feat(rup): saca mdi

cypress/integration/apps/solicitud/referir-solicitud.spec.js
Por algunos cambios que se hicieron en la api cambiar la palabra "referencia" por "referir"
=> fix(TOP): cambia la palabra referencia por referir

cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/plugins/seed-prestaciones.js
=> punto inicio rup: lazy load pendientes

cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
Se actualizan dos test pausados ("skip") para poder tester similitud con pacientes temporales.
1. crear paciente con similitud del 98% con uno existente temporal y seleccionarlo para guardar
2. crear paciente con similitud del 81% con uno existente temporal
- [] Si
=> MPI: Se actualizan test mpi  con similitud entre pacientes temporales

cypress/support/index.d.ts
Agregar plex para autocompletado
1. Se agregó **plex select: default, type, async**
2. Se agregó **plex badge**
3. Se agregó **plex toast**
4. Se agregó **plex datetime**
5. Se agregó **plex dropdown**
6. Se agregó **plex bool**
7. Se agregó **plex textArea**
- [] Si
- [] No
=> refactor: agrega nuevos plex autocompletado

cypress/integration/apps/auditoria/auditoria.spec.js
Se corrige un test de auditoría
1. Test corregido "vincular dos pacientes sin documento"
2. 
3.
=> MPI: se corrige test en auditoría

cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/core/mpi/mpi-registro-bebe.spec.js
https://proyectos.andes.gob.ar/browse/MPI-212
1. Reemplaza label "fecha de nacimiento" por "fecha y hora de nacimiento"
2. Se modifica acceso a boton para confirmar nota registrando paciente
=> MPI - agrega hora nacimiento en alta de bebe

cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js
Elimina wizard de los tests de solicitudes ya que se quitó del formulario de nueva solicitud
=> feat(top): Quita wizard que se reemplazo por hint

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/support/index.js
Fix en el test de edicion de agenda publicada para que funcione de manera correcta con el nuevo cambio de deteccion de errores que se logean en la consola.
1. Se agrega wait para el correcto funcionamiento del test.
2. Se modifica get por plexSelect.
=> Fix editar agenda

cypress/integration/apps/rup/internacion/epicrisis.spec.js, cypress/support/index.js
Hack para descubrir si algún test tiro un error en la consola y no se esta handleando. 
Hay varios test que fallan ahora. Estaría bueno corregir los bugs y mergear esta feature. 
https://dashboard.cypress.io/projects/xr7gft/runs/1008/specs
1. 
2. 
3.
=> test: check errors

cypress/integration/apps/rup/punto-inicio/punto-inicio-navegacion.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, data/modulos/modulos_basic.json
=> feat(huds): nuevas rutas

cypress/integration/apps/auditoria/auditoria.spec.js, cypress/integration/apps/auditoria/reportarError.spec.js, cypress/plugins/seed-paciente.js
Actualizacion por refactor visual de auditoria
1. Se actualizan casos de test.
2. Se agregan casos de correccion de pacientes con errores
- [] Si
=> MPI - Refactor auditoria

cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js
1. Se agrega condición para pasado mañana para que vaya hacia la derecha en el calendario y encuentre la agenda
=> fix(TOP): agrega condicion para controlar fin de mes

cypress/integration/apps/rup/internacion/epicrisis.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js
https://proyectos.andes.gob.ar/browse/MPI-242
1. Actualiza visualizacion de listado de pacientes internacion (epicrisist)
=> MPI - Adapta a visualizacion de listado de pacientes

cypress/integration/apps/com/com.spec.js, data/authUsers/authUsers_basic.json, data/organizacion/organizacion_basic.json, data/reglasDerivacion/reglas_derivacion_basic.json
https://proyectos.andes.gob.ar/browse/COM-13
1. Se modifican los datos de la base de prueba
2. Nuevos tests para módulo COM
=> COM: nuevos tests para centro operativo médico

cypress/fixtures/mitos/fiebre.json, cypress/fixtures/mitos/frecuentes.json, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/rup/ejecucion/agregar-conceptos.spec.ts, cypress/integration/apps/rup/ejecucion/agregar-huds.spec.ts, cypress/integration/core/auth/login.spec.js, cypress/plugins/data/prestacion/registro.json, cypress/plugins/seed-prestaciones.js, cypress/support/commands.js, cypress/support/index.d.ts, cypress/support/plex.js, cypress/support/rup.js
Agregar test de conceptos en rup, evoluciones y que no se puedan repetir. 
Para agregar lo mismo sobre una sección
=> test(rup): test de conceptos y otros

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
1. Se verifica si el día de ayer fue el último día del mes anterior para así mover el calendario al mes actual y poder clonar con éxito.
=> fix(CITAS): Condición en Planificación de agendas

cypress/integration/apps/rup/elementos-rup/repetir-registro.spec.ts, cypress/plugins/database-initial.js, cypress/plugins/database.js, cypress/plugins/index.js, cypress/plugins/seed-elementos-rup.js, cypress/support/index.d.ts
test para repetir conceptos elementos rup
1. 
2. 
3.
=> test(rup): test de elementos rup repetidos

cypress/integration/apps/visualizacion-informacion/bi-queries.spec.js, cypress/support/plex.js, data/authUsers/authUsers_basic.json, data/modulos/modulos_basic.json
https://proyectos.andes.gob.ar/projects/BI/issues/BI-54?filter=allopenissues
1. Se crea test para el nuevo componente _bi-queries_.
2. Se agregan los comandos _plexSelectTypeDinamico_,  _plexBoolDinamico_ y _plexBoolDinamico_, para utilizar en el nuevo test, ya que los distintos filtros son creados dinamicamente.
3. Se modifican en la colección _authUsers_ los nuevos permisos.
4. Se agrega en la colección _modulos_ el nuevo _Visualización de información_ y se eliminan el modulo _reportes_ y _dashboard_.
=> Visualización de información: Test para visualizacion de informacion

cypress/integration/apps/puco/puco.spec.js
1. Se agrega login 
2. Se cambia en el route profe por puco
=> fix(PUCO): agrega login al test

data/authUsers/authUsers_basic.json
Arreglar tests de COM para que funcionen con los nuevos permisos
1. Se suma el permiso com:* a las organizaciones de los usuarios involucradas en los tests
=> COM: se suman permisos a organizaciones

cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/rup/ejecucion.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js, cypress/integration/core/auth/select-organizacion.spec.js
Quita algunos wait yas que se eliminan de la APP por performance. 
1. 
2. 
3.
=> fix(test): hay rutas que no se hacen mas por cache

cypress/integration/apps/citas/agendas/gestor_agendas_listado.spec.js, cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js
1. Se aplicaron cambios según modificaciones de plex-help
2. Se aplicaron cambios según modificaciones de plex-detail
=> fix: actualiza selectores para plex v7.2.0

cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js
=> feat(citas): lazy load

cypress/integration/apps/com/com.spec.js
https://proyectos.andes.gob.ar/browse/COM-19
1. Nuevo tests para sumar nota a una derivación
=> COM: tests para sumar nota/adjunto

cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/integration/apps/solicitud/referir-solicitud.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js
Arreglo de tests para https://github.com/andes/app/pull/1824
1. Se adaptaron todos los spec correspondientes a la carpeta _solicitudes_
- [] Si
=> TOP: arreglo de tests para refactor de listado de solicitudes

cypress/integration/apps/rup/internacion/camas/camas.spec.js, cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js, cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js, cypress/integration/apps/rup/internacion/listado-internacion/romper-validar.spec.js, cypress/integration/apps/rup/internacion/medica/egresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/movimientos.spec.js, cypress/integration/apps/rup/internacion/salas-comunes/salas-comunes.spec.js, cypress/plugins/data/internacion/sala-default.json, cypress/plugins/data/internacion/sala-snapshot.json, cypress/plugins/index.js, cypress/plugins/seed-internacion.js, cypress/support/mapa-camas.js, cypress/support/plex.js
Agrega los primeros tests de sala comun: alta, modificación, ingreso, egreso y movimientos a camas.
1. Agrega los siguientes tests de sala comun: alta, modificación, ingreso, egreso y movimientos a camas
2. 
3.
=> INTERNACION - Tests de sala comun

cypress/integration/apps/rup/internacion/medica/egresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/movimientos.spec.js, cypress/integration/apps/rup/internacion/medica/registros.spec.ts, cypress/support/seed.js
=> test(mapa-camas): test para efermeria

cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js, cypress/plugins/seed-internacion.js, cypress/support/mapa-camas.js
Agrega test para deshacer internacion.
1. Agrega test para deshacer internacion.
2. 
3.
=> INTERNACION - Agrega test para deshacer internacion

cypress/integration/monitoreo/modulos.spec.js, data/modulos/modulos_basic.json
- Actualizar tests para funcionar con submódulos
- Agregar tests para submódulos
1. Se modificó el acceso a diferentes campos de formulario que ahora son reactivos
2. Se incorporaron tests específicos para submódulos
=> feat(monitoreo): tests de submódulos

cypress/integration/apps/auditoria/auditoria.spec.ts
Revisar y mejorar test de auditoría ya que hacen un retry (fallan las primeras veces que se ejecuta).
1. Se modificaron y especificaron contenidos en algunos elementos para que cypress los pueda encontrar al dar "click": se observó que fallaba al no poder decidir en qué elemento hacer "click".
2.  Se cambió el archivo modificado con la extensión "ts"
3.
=> Se mejoran test que fallan en los primeros intentos

cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/integration/apps/solicitud/referir-solicitud.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js
https://proyectos.andes.gob.ar/browse/TOP-85
1. Verifica generación de historial de solicitud
2. 
3.
=> TOP: Verifica generación de historial de solicitud

cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/plugins/data/agendas/agenda-default.json, cypress/plugins/seed-agenda.js
https://proyectos.andes.gob.ar/browse/RUP-124
1. Agrega test de anulacion de prestaciones iniciadas para los 4 tipos de agenda
=> RUP - Invalidar inicio de prestación

cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/integration/apps/solicitud/referir-solicitud.spec.js
Controlar historial en tests de TOP
1. Control de historial de solicitudes en tests de TOP
=> TOP: control de historial en tests

cypress/integration/apps/rup/elementos-rup/seccionado.spec.js, cypress/support/rup.js, data/elementosRUP/elementosRUP_basic.json
Ajuste del selector de iconos de semantic tags. Evito tocar todos los archivos de RUP.
=> refactor(rup): change icon name

cypress/integration/apps/rup/internacion/medica/egresos.spec.js, cypress/integration/apps/rup/internacion/medica/movimientos.spec.js, cypress/support/mapa-camas.js
Ajusta test de sala
1. 
2. 
3.
=> test(mapa-camas): test sala siempre visible

cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js
1. Se cambia la variable pasadoManiana ya que estaba sumando 3 días al día de la fecha 
2. Se cambia en liberarTurnoSolicitud la variable pasadoManiana y la fecha de la agenda para que tenga coherencia.
3.
=> fix(TOP): calendario

cypress/integration/apps/auditoria/auditoria.spec.ts, cypress/support/index.d.ts
1. Se agregaron wait de PUT al confirmar la desvinculación
2. Se agregó texto adicional en toast y swal
=> fix(TEST): Auditoria flaky

.jenkins/mobile.jenkins, .jenkins/test.jenkins, docker/andes.Dockerfile, docker/nginx.conf
Incluye la app mobile a nginx
https://proyectos.andes.gob.ar/browse/AM-58
1. Incluye la app mobile a nginx
2. 
3.
=> MOBILE APP: incluye mobileapp a nginx

cypress/integration/apps/com/com.spec.js, cypress/support/plex.js
1. Se agregan unos wait en crear derivacion, aprobarla, asignarla, aceptarla, finalizarla luego de que se selecciona un paciente
2. Se agregan unos wait en crear derivacion, aprobarla, asignarla, rechazarla, finalizarla luego de que se selecciona un paciente
3. Se agrega el force:true al clearSelect
=> fix(COM): COM Flaky

cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js
Agrega control de anulación de prestacion al deshacer internacion.
1. Controla que se anule la prestacion al deshacer internacion.
2. 
3.
=> INTERNACION - Anular prestacion al deshacer internacion

cypress/integration/apps/gestor-usuarios/usuarios.spec.js
=> fix(TOP): agrega force true a test de asignar perfil

cypress/integration/monitoreo/activaciones-app-mobile.spec.js
1. Se agrega control para que antes de buscar al paciente, verifique la cantidad de filas que tiene la tabla sea 1
=> fix(MONITOREO): monitoreo de activaciones FLAKY

cypress/integration/apps/com/com.spec.js
Arreglo de test de COM para rama COM-29
1. Se suman waits y uso de filtros para listar derivaciones
=> COM: arreglo de tests de com

cypress/integration/apps/huds/huds.spec.ts
Volver agregar los test de HUDS que se perdieron al mergear https://github.com/andes/andes-test-integracion/pull/264
=> feat(HUDS): test huds

cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js
Arreglar tests para PR https://github.com/andes/app/pull/1958
1. Control del tab historial
=> TOP: arreglo de tests

cypress/fixtures/mpi/paciente-validado4.json, cypress/integration/core/mpi/mpi-registro-con-dni.spec.js
1. Se extiende caso de validacion de paciente, deshaciendo y validando con otros datos. Luego se verifica que no se hayan 'filtrado' datos de la primera validación.
=> MPI - Casos validar y deshacer validacion por renaper

cypress/integration/apps/huds/huds.spec.ts, cypress/plugins/seed-prestaciones.js, data/conceptoTurneable/conceptoTurneable_basic.json, scripts/github.js
https://proyectos.andes.gob.ar/browse/HUDS-28
1. Agrega test para ambito internación y verificar rapidamente los datos de la epicrisis médica
=> HUDS: Test internacion

cypress/integration/apps/auditoria/auditoria.spec.ts
https://proyectos.andes.gob.ar/browse/MPI-283
1. Se adaptan test a cambios en las rutas de servicio paciente
=> MPI - Nuevas rutas en auditoria

cypress/integration/core/tm/profesional/profesional.spec.ts
Actualizar rutas de validacion de profesionales
1. Adapta casos de test en profesionales
=> TM - Nueva ruta para validacion de profesionales

cypress/integration/apps/com/com.spec.js
Arreglo de tests para https://github.com/andes/app/pull/2031
1. Aplica filtro de estado antes de sumar nota en test
=> COM: arreglo de tests para com

cypress/integration/apps/rup/internacion/camas/camas.spec.js, cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js, cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js, cypress/integration/apps/rup/internacion/listado-internacion/romper-validar.spec.js, cypress/integration/apps/rup/internacion/mapa-camas/detalle-cama.spec.js, cypress/integration/apps/rup/internacion/mapa-camas/filtros-camas.spec.js, cypress/integration/apps/rup/internacion/medica/egresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/movimientos.spec.js, cypress/integration/apps/rup/internacion/medica/registros.spec.ts, cypress/integration/apps/rup/internacion/salas-comunes/salas-comunes.spec.js, data/modulos/modulos_basic.json
Al cambiar las rutas del mapa de camas hay que refactorizar los tests.
1. Refactoriza los tests para adecuarlos a las nuevas rutas del mapa de camas
2. 
3.
=> INTERNACION - Adapta tests a las nuevas rutas del mapa de camas

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js, cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/gestor_agendas_listado.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.js, cypress/integration/apps/citas/turnos/punto_inicio.spec.ts, cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/gestor-usuarios/perfiles.spec.js, cypress/integration/apps/rup/colonoscopia.spec.js, cypress/integration/apps/rup/ejecucion.spec.js, cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/integration/apps/solicitud/referirSolicitud.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/support/index.d.ts
Cambio la ruta de tipoPrestacion y la lógicas de los plex-select.
=> refactor(conceptos-turneables): cambio de rutas

cypress/integration/apps/com/com.spec.js
Arreglo de tests para https://github.com/andes/app/pull/2048
1. Cambios en control de historial en tests de COM
=> COM: arreglo de tests para refactor de historial

cypress/integration/apps/rup/elementos-rup/atomo-checklist.spec.ts, cypress/support/index.d.ts, cypress/support/plex.js
Test para la compoenente CheckListComponenet de Elementos RUP
=> feat(rup): test check list

cypress/integration/apps/rup/elementos-rup/reglas-dinamicas.spec.ts, cypress/plugins/seed-elementos-rup.js
=> test reglas dinamicas rup

cypress/integration/apps/solicitud/solicitudes.spec.js
=> fix(top): change placeholder

cypress/integration/core/tm/profesional/profesional.spec.ts
https://proyectos.andes.gob.ar/browse/MPI-302
=> TM - Modifica response en validación por FA

cypress/integration/apps/auditoria/reportarError.spec.ts
Mariano Botta:voleibol:  08:30
Buenas!
Tenemos estos test que están fallando siempre:
https://dashboard.cypress.io/projects/xr7gft/runs/1987/test-results
1. Corrige labels y reemplaza js por ts
=> Auditoria - Fix en reporte de errores

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js
https://proyectos.andes.gob.ar/browse/CIT-87
1. Incluye test de revisión de agenda dinámica: agregar paciente
2. 
3.
=> CITAS: Revisión agenda dinámica agregar paciente

cypress/integration/apps/citas/turnos/punto_inicio.spec.ts, cypress/integration/apps/gestor-usuarios/usuarios.spec.js, cypress/integration/apps/rup/internacion/camas/camas.spec.js
=> feat(chore): ajustes ivy

cypress/integration/apps/com/com.spec.js
Modificar tests de COM para ramas COM-49 de app/api
1. Cambio de textos en test de sumar nota
=> COM: actualización de textos para pr de cambio de prioridad

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
1. Agrega un wait para que luego de seleccionar el boton de editar, espere que se cargue el panel lateral y poder seguir correctamente con el test.
=> fix(CITAS): agrega wait para evitar flaky en jenkins

cypress/integration/core/tm/profesional/profesional.spec.ts
Se modifica test en validacion de profesionales
1. 
2. 
3.
=> Se modifica test en validacion

cypress/integration/apps/rup/elementos-rup/atomo-checklist.spec.ts
Casos de test para poder elegir otros
=> test(rup): checklist con otros

cypress/integration/apps/mobile/mobile-profesional.spec.ts
=> test(rup): ajuste ruta andes drive

cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js
Se modifica test para https://github.com/andes/app/pull/2127
1. Se saca del test de campos requeridos el control sobre profesionalOrigen
=> TOP: cambio en test de campos requeridos

cypress/integration/apps/mobile/mobile-paciente.spec.ts, cypress/integration/apps/mobile/mobile-profesional.spec.ts, cypress/plugins/seed-nomivac.js, cypress/support/index.js
Arreglar y modificar test para la nueva version de app mobile
1. Se arreglaron test  mobile-profesional en general
2. Se arreglo test de "modificación de email" en mobile-paciente
3. Se agrego test de "modificacion de datos de acceso" en mobile-paciente
4. Se agrego test de "cambiar contraseña" en mobile-paciente
5. Se agrego un simple test para verificar historial de turnos
=> TEST- Fix mobile paciente y profesional

cypress/integration/apps/com/com.spec.js, data/authUsers/authUsers_basic.json, data/organizacion/organizacion_basic.json, data/tipoTraslado/tipoTraslado.json
https://proyectos.andes.gob.ar/browse/COM-53
Test para traslados especiales en derivaciones COM
1. 
2. 
3.
=> COM: test traslado especial

scripts/github.js
Agregar badge con el resultado de los tests en el repositorio de la app mobile
1. Se modifica script de github
=> chore(cypress): Agrega test result de app mobile en github

.github/CODEOWNERS, cypress/integration/apps/com/com.spec.js
Pequeño fix a los test del COM. Habría que revisar correctamente los wait de derivaciones
=> fix(com): test traslado

cypress/integration/apps/citas/turnos/punto_inicio.spec.ts
https://proyectos.andes.gob.ar/browse/MPI-327
1. Carga un numero de telefono con formato valido
=> MPI - Corrige edición de contactos en ventanilla

cypress/integration/apps/huds/huds.spec.ts, cypress/integration/apps/rup/elementos-rup/seccionado.spec.js
se corrigen test que fallaron en jenkins  3450 
1. seccionado.spect se cambio el text-area por plex-text
2. huds.spect se saca el espacio en texto de epicrisis.
3.
=> fix(RUP):se corrige test de seccionado y huds

cypress/integration/apps/huds/huds.spec.ts
Agregar test para filtrar por organizacion en la huds
=> feat(HUDS):filtro por organizacion en huds

cypress/integration/apps/mobile/mobile-paciente.spec.ts, cypress/support/commands.js
https://proyectos.andes.gob.ar/browse/AM-125
Reemplaza https://github.com/andes/andes-test-integracion/pull/323
1. Se arregla test skipeado, el cual se debe probar con el PR andes/mobile-app#135
=> test(MOBILE): Arreglo dación de turno paciente

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts, cypress/support/index.d.ts, cypress/support/plex.js, data/authUsers/authUsers_basic.json, data/forms/forms_basic.json
https://proyectos.andes.gob.ar/browse/EP-14
1. Se crean test para crear/editar ficha de tipo covid 19.
2. Se agrega el formulario a la base de datos.
3. Se agrega el comando plexIcon.
4. Se agregan comandos usados al index.
=> FICHA EPIDEMIOLOGICA: Test para ficha

data/organizacion/organizacion_basic.json
- Se agrega email en la configuración de organización COM
=> feat(com): add email to COM organization

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts
https://proyectos.andes.gob.ar/browse/EP-25
1. Actualiza nuevos campos
Perdona por el nombre de la rama, me equivoque en otra.
=> FICHA-EPIDEMIOLÓGICA: Actualizacion ficha COVID-19

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts, data/forms/forms_basic.json
https://proyectos.andes.gob.ar/browse/EP-27
1. Se actualiza la ficha en base a nuevos cambios.
=> FICHA-EPIDEMIOLOGICA: Actualizaciones

cypress/integration/apps/epidemiologia/buscador-ficha-epidemiologica.spec.ts, cypress/plugins/seed-paciente.js, data/formsEpidemiologia/formsEpidemiologia_basic.json
https://proyectos.andes.gob.ar/browse/EP-23
1. Se agregan test para el buscador de fichas epidemiologicas.
2. Se agrega una ficha de tipo 'covid 19' para usar en los test.
3. Se agrega en seed-paciente la posibilidad de crear un paciente enviando por parametro un '_id'.
=> EPIDEMIOLOGIA: Buscador de fichas epidemiologicas

cypress/integration/apps/epidemiologia/buscador-ficha-epidemiologica.spec.ts, cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts, data/forms/forms_basic.json, data/formsEpidemiologia/formsEpidemiologia_basic.json
Actualizar ficha con nuevos campos de provincia y localidad de residencia
1. Se actualiza el form y los campos en los test para la nueva ficha
=> FICHA EPIDEMIOLOGICA: Localidades y provincia

cypress/integration/apps/epidemiologia/buscador-ficha-epidemiologica.spec.ts, data/formsEpidemiologia/formsEpidemiologia_basic.json
Fix test buscador de fichas epidemiologicas.
1. Cambia el campo type a un Object.
=> EPIDEMIOLOGIA: Nueva ficha

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts, cypress/plugins/seed-paciente.js, data/forms/forms_basic.json
Fix para los test de creación/edición de ficha epidemiológica según los nuevos requerimientos de la sección MPI
1. Se agrega al create:paciente la opción de enviar una dirección del paciente.
2. Se eliminan de los test los campos que se cargan automáticamente.
3. Se agrega el campo dirección en el fixture de la ficha.
=> FICHA EPIDEMIOLÓGICA: Modificaciones por actualizaciones MPI y dirección en el seed de paciente

cypress/fixtures/form/form-example.json, cypress/integration/apps/forms/form-builder/form-builder.spec.js, data/authUsers/authUsers_basic.json, data/formResources/formResources.json, data/forms/forms_basic.json
https://proyectos.andes.gob.ar/browse/EP-20
Test form builder. Correr con https://github.com/andes/app/pull/2219
1. 
2. 
3.
=> test form-builder

data/forms/forms_basic.json
Actualizar el tipo de dato fechasintomas.
1. Se modifica el campo fecha de inicio de síntomas, pasa de ser de dependencia a tipo date por las nuevas actualizaciones de la ficha.
=> FICHA EPIDEMIOLOGICA: Actualizacion en tipo de dato fechasintomas

cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/integration/apps/solicitud/solicitudes.spec.js
Adaptar los tests para el nuevo control de solicitudes duplicadas
1. Se cambian tipos de prestaciones destino en tests de top
=> TOP: cambios en tests para nuevo control de solicitudes duplicadas

data/profesional/profesional_basic.json
=> feat(profesionales): tokens

cypress/integration/apps/mobile/mobile-paciente.spec.ts
Corrige test de modificación de mail en paciente mobile.
1. 
2. 
3.
=> AM(paciente): fix en test modificacion de mail

cypress.json, cypress/integration/apps/com/com.spec.js
1. Se modifica el test de creación de derivación con impresión de historial debido a error en descarga de pdf.
2. Se agrega route2 (anteriormende denominado intercept) para reescribir el response.
=> feat(com): Add interceptor to rewrite route response

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts
Modificar los campos de ficha según las nuevas actualizaciones.
1. Se modifica la sección segunda clasificación dados los nuevos requerimientos.
=> FICHA-EPIDEMIOLOGICA: Cambios en seccion segunda clasificación

cypress/integration/apps/com/com.spec.js
=> remove print button

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts, cypress/plugins/seed-paciente.js, cypress/support/index.d.ts, data/authUsers/authUsers_basic.json, data/grupo-poblacional/grupo-poblacional_basic.json, data/inscripcion-vacunas/inscripcion-vacunas_basic.json
https://proyectos.andes.gob.ar/browse/VAC-54
1. Test de filtros
2. Test para verificar datos en sidebar y listado
3. Cambio de grupo
4. Agregar diferentes tipo de notas
5. Nueva inscripcion
6. Verificación para salga el cartel de que ya esta inscripto
7. Verificación para no poder editar paciente vacunado
=> feat(VAC): test en listado de inscriptos

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
Actualizar test de notas con los cambios actuales
=> fix(VAC): Notas listado de inscriptos

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
Al agregarse un estado nuevo, fallaban los test de cambio de estado
=> VAC -  Arreglo al seleccionar combo de estados

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
Agregar test de estado fallecido en listado de inscriptos de vacunación.
=> feat(VAC): agrega test de estado fallecido

cypress/integration/apps/rup/internacion/estadistica/ingresos.spec.js, cypress/integration/apps/rup/internacion/medica/ingresos.spec.js
=> feat(mapa-camas): intercept snomed search

cypress/integration/core/tm/organizacion/organizacion.spec.ts, data/zonasSanitarias/zonasSanitarias_basic.json
Se agregan test para la tarea https://proyectos.andes.gob.ar/browse/MISC-156
1. Se agrego una colección nueva llamada zonaSanitaria en la base de datos. 
2. Se agrego la funcionalidad para poder agregar o cambiar una zona sanitaria de un efector.
=> feat(Organizacion): Agregar test en zona sanitaria

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
https://dashboard.cypress.io/projects/xr7gft/runs/3138/test-results/0dc09b2b-cfca-4b7f-910a-8a1293baa86f
1. Momentaneamente se saca el plex-radio del test de vacunacion, el cual seleccionaba la relación laboral del paciente
=> fix(VAC):saca momentaneamente el plexradio de relacion laboral

data/forms/forms_basic.json
Fix en el campo fechasintomas
1. Se modifica a dependencia en el campo fecha de inicio de síntomas, por la nueva actualización de la ficha.
=> FICHA EPIDEMIOLOGICA: Cambio campo fecha sintomas

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts, data/inscripcion-vacunas/inscripcion-vacunas_basic.json
1. Se realiza una verificación de los datos email y teléfono al editar
=> fix(VAC): verificacion de email y telefono correctos

cypress/integration/apps/citas/turnos/turnos.spec.js
1. 
2. 
3. 
https://github.com/andes/app/pull/2260
=> MPI:agrega patrón en campo nombre

cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js, cypress/integration/apps/rup/internacion/medica/egresos.spec.js
=> feat(mapa-camas): ajustes label fecha egreso

cypress/integration/apps/solicitud/solicitudes.spec.js
https://proyectos.andes.gob.ar/browse/TOP-114
1. Se modifico test para que controle que todos los datos de la regla se guarden correctamente
2. Se agregaron dos test simples solo para controlar los carteles cuando falta organización origen o falta prestación destino
3.
=> fix(TOP): modificacion en test de reglas de entrada

cypress/plugins/seed-internacion.js
Agrega estadoActual en el seed de prestaciones de estadistica.
=> fix(mapa-camsa): faltaba estadoActual en prestacion

cypress/integration/apps/com/com.spec.js, cypress/plugins/colleciones.json, data/dispositivo/dispositivo_basic.json
Se realizan los test para la nueva funcionalidad del COM, dispositivos de oxigeno.
https://proyectos.andes.gob.ar/browse/COM-83
=> feat(COM): Test de dispositivos de oxigeno

cypress/integration/apps/rup/elementos-rup/elemtos-rup-requeridos.spec.ts, cypress/plugins/index.js, cypress/plugins/seed-elementos-rup-requeridos.js, cypress/plugins/seed-services.js
Test de elementos rup requeridos
=> feat(rup): test elementos requeridos

data/andes-services/andes-services_basic.json
=> feat(rup): agrega servicio

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
https://proyectos.andes.gob.ar/browse/VAC-82
1. Se saca test que verificaba que los pacientes que estaban vacunados no tengan el boton de editar activado
=> fix(VAC): Editar la inscripción

cypress/integration/apps/gestor-usuarios/perfiles.spec.js
=> feat(rup): ajustes test

cypress/integration/apps/mobile/mobile-paciente.spec.ts
https://proyectos.andes.gob.ar/browse/MISC-173
1. Se elimino la fecha desde y hasta de las campañas de salud
=> fix(camp): Eliminacion de fechas desde y hasta

data/formResources/formResources.json, data/forms/forms_basic.json, data/formsEpidemiologia/formsEpidemiologia_basic.json
Fix test para seguimiento epidemiológico
1. 
2. 
3.
=> Fix test para seguimiento epidemiológico

cypress/integration/core/mpi/mpi-registro-con-dni.spec.ts
https://proyectos.andes.gob.ar/browse/MPI-355
1. Se crearon distintos test para verificar el lugar de nacimiento del paciente.
=> feat(MPI-355) Se agregaron test para lugar de nacimiento

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts, data/forms/forms_basic.json
Test de carga parcial de ficha y actualizacion de data de fichas.
1. 
2. 
3.
=> EP: ficha carga parcial

cypress/integration/apps/mobile/mobile-paciente.spec.ts
Fix by @andrrrl, Agrega waitFor antes de los gets de botones para esperar a la transición entre páginas 
1. Agrega waitFor antes de los gets de botones
=> fix app mobile tests

cypress/integration/apps/epidemiologia/buscador-ficha-epidemiologica.spec.ts
Modificar test por inclusión de collapse en app.
1. Se agrega un clip para abrir los filtros y se corrige un error de ortografía.
=> Buscado Epidemiología: Agrega collapse en app

data/elementosRUP/elementosRUP_basic.json
dispatch seguimiento covid
1. 
2. 
3.
=> dispatch seguimiento covid

cypress/integration/apps/rup/internacion/medica/registros.spec.ts
=> IN - Fix registros por capa

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts
=> fix referencia history ficha

data/semaforo/semaforo.json
Datos de registro de semaforo del COM
1. 
2. 
3.
=> MISC: data semaforo

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts, data/grupo-poblacional/grupo-poblacional_basic.json
https://proyectos.andes.gob.ar/browse/VAC-99
1. Actualización de grupos poblacionales acorde a los datos que están en producción actualmente
=> VAC - Modificación grupo poblacionales

cypress/integration/core/tm/organizacion/organizacion.spec.ts
https://proyectos.andes.gob.ar/browse/MISC-190
1. Ajusta búsqueda de elementos a tabla plex.
=> TM organizaciones: Agregar permiso global

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
https://proyectos.andes.gob.ar/browse/VAC-103
1. Ajusta test a cambios en app
=> ref(vac): ajusta combo de estados de inscripciones

cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts
https://proyectos.andes.gob.ar/browse/VAC-61
=> VAC - Notas en listado de inscriptos

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js, data/authUsers/authUsers_basic.json
Crear test para la nueva funcionalidad de asignación de seguimientos de casos.
1. Se crea un test que asigna un profesional y una organización a un seguimiento.
=> EPIDEMIOLOGÍA - Test para asignación de segumiento

cypress/integration/apps/com/com.spec.js, cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts, cypress/integration/apps/rup/ejecucion/agregar-conceptos.spec.ts, cypress/integration/apps/solicitud/solicitudes.spec.js, cypress/support/index.js
pequeños ajustes con la nueva version de plex
=> ajustes version de plex

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts
=> EP: registrar concepto c19 confirmado

data/formsEpidemiologia/formsEpidemiologia_basic.json
=> EP: active true ficha

cypress/integration/apps/perinatal/control-alertas.spec.ts, cypress/plugins/seed-carnet-perinatal.js
https://proyectos.andes.gob.ar/browse/PER-58
1. Se agregaron nuevos controles para verificar si un paciente tiene el control de embarazo vencido, que figure en alertas y chequear los datos que salen.
=> Agregando nuevos testeos en el modulo de perinatal

cypress/integration/apps/puco/puco.spec.js
Arreglar los tests de puco para https://github.com/andes/app/pull/2530
1. Cambio en búsqueda de elemento plex
=> MISC: arreglo de test de puco para PR de refactor

cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/citas/turnos/turnos.spec.js, cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js
Modificar test de acuerdo al nuevo header de la pantalla dar turnos.
1. Se modifican respuestas de la api, verificación de labels y botones.
=> CITAS - Nuevo header turnos

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas.spec.js
refactor de tests para https://proyectos.andes.gob.ar/browse/CIT-137
=> CITAS (Fix) - Turno en agenda no nominalizada ya auditada

cypress/integration/apps/perinatal/listado-pacientes.spec.ts
Modificar verificación de edad en el paciente andes validado en el listado de pacientes
=> PER - modifica edad del paciente

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
https://proyectos.andes.gob.ar/browse/CIT-158
1. Se actualizo la ruta POST de clonar agenda ya que la misma fue modificada dentro de la api
=> CIT- modal para crear o actualizar agendas

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js, data/seguimientoPacientes/seguimientoPacientes_basic.json
https://proyectos.andes.gob.ar/browse/EP-191
1. Se asocia el seguimiento a la ficha por las nuevas restricciones.
=> Seguimiento - Modificar control en epidemiologia:prestaciones:validate (primer seguimiento)

cypress/integration/apps/vacunacion/estado.spec.ts, data/pacientes-vacunas/pacientes-vacunas_basic.json
https://proyectos.andes.gob.ar/browse/VAC-125
1. Se agregan test para la nueva pantalla de estado de vacunación de pacientes.
=> Vacunas - Test para consulta de estado de vacunacion de los pacientes

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js, cypress/integration/apps/visualizacion-informacion/exportar-huds.spec.ts
https://proyectos.andes.gob.ar/browse/MISC-213
1. Al cambiar plex-list por plex-table, se tuvieron que actualizar los test que fallaban
=> TURNOS y PRESTACIONES: cambia plex list por plex table

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js, data/semaforo/semaforo.json
https://proyectos.andes.gob.ar/browse/EP-198
1. Se modifican los test de seguimiento por los nuevos cambios en los filtros.
=> Seguimiento - Agregar ordenamiento por fecha o prioridad

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js
=> Seguimiento - fix test asignacion

cypress/integration/core/tm/profesional/profesional.spec.ts
https://proyectos.andes.gob.ar/browse/TM-20
=> TM - Actualización de test de profesional

cypress/fixtures/form/form-example.json, cypress/integration/apps/forms/form-builder/form-builder.spec.js
https://proyectos.andes.gob.ar/browse/EP-107
1. Se modifica el test por el refactor visual del form builder.
=> FORM - Refactor Form Builder 

cypress/integration/apps/citas/turnos/dar_turno.spec.js, cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js
https://proyectos.andes.gob.ar/browse/CIT-119
1. Se cambia boton cancelar por demanda rechazada
=> CITAS -  cambia botón de cancelar por demanda rechazada

cypress/integration/apps/rup/internacion/medica/registros.spec.ts
https://proyectos.andes.gob.ar/browse/IN-431
1. Se agrego la fecha junto con la hora dentro del plexLayoutMain
=> IN - Mostrar fecha y hora del mapa de cama

data/conceptoTurneable/conceptoTurneable_basic.json
https://proyectos.andes.gob.ar/browse/TOP-127
1. Se agrego el atributo "ambulatorio" a la prestación consulta de medicina general
=> TOP - Agregar atributo ambulatorio en prestaciones

cypress/integration/apps/rup/internacion/estadistica/egresos.spec.js
[IN-413](https://proyectos.andes.gob.ar/browse/IN-413) - Egreso de una internacion: Modificar label
1. Se modificaron los test para que selecciones los labels de manera apropiada.
2. 
3.
=> style(IN): se cambian labels por mas descriptivos

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js
Modifcar respuestas de la api por la paginacion.
1. Se modifica el control de las respuestas en la api por el nuevo modo de paginacion en los resultados.
2. 
3.
=> Seguimiento - Cambios en paginacion

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js, cypress/integration/apps/rup/ejecucion.spec.js
https://proyectos.andes.gob.ar/browse/IN-441
1. Solo correccion
=> IN - Capa medica, nuevo registro no precarga fecha y hora

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/gestor_agendas_listado.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js, cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js
https://proyectos.andes.gob.ar/browse/CIT-173
=> CITAS- Gestor de agendas

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js, cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
Quedaron desactualizados algunos test en el refactor de listado de gestor de agendas
=> CITAS -  Cambios por actualizacion de listado de gestor agendas

cypress/integration/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/integration/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/integration/apps/rup/internacion/medica/ingresos.spec.ts, cypress/plugins/database.js, cypress/plugins/seed-internacion.js, cypress/support/mapa-camas.js, data/organizacion/organizacion_basic.json
https://proyectos.andes.gob.ar/browse/IN-447
1. Se corrigieron los test de internacion y por el momento se omitió un test hasta que se resuelva un bug que ocurre en la capa de estadística nueva.
=> fix(IN-447): Correccion de test en internacion

cypress/integration/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/integration/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/plugins/seed-internacion.js, cypress/support/mapa-camas.js, data/organizacion/organizacion_basic.json
https://proyectos.andes.gob.ar/browse/IN-461
1. Se corrigieron los test que ingresos de capa estadistica unificada.
=> IN - Test de internacion en capa unificada

cypress/integration/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/integration/apps/rup/internacion/medica/egresos.spec.ts
https://proyectos.andes.gob.ar/browse/IN-460
1. Corrige mensaje de toast
- [X No
=> IN (Fix) - Error en fechas de egreso

cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.js
https://proyectos.andes.gob.ar/browse/CIT-177
=> CITAS - Actualización test de gestor y planificación de agendas

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, cypress/e2e/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js, cypress/support/commands.js, docker/nginx.conf
=> Fix gestor agenda

cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts
Actualizacion plex
1. Se modifica test al que afecta la actualización de plex.
2. 
3.
=>  Core - Actualizacion plex

cypress/support/seed.js
Corregir test internacion
1. Se agrega la coleccion internacionPacienteResumen al seed para que evitar internaciones en curso al momento de ingresar pacientes
=> Fix test sala comun

cypress/e2e/apps/rup/internacion/camas/camas.spec.ts, cypress/e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica/egresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts, cypress/e2e/apps/rup/internacion/medica/egresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/movimientos.spec.ts
https://proyectos.andes.gob.ar/browse/IN-491
1. Se adaptan tests a cambios en api
=> IN - Error al editar camas

cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts
1. Corrige get de plex-button para edicion de internación, que fallaba cada tanto.
=> IN - Ingreso en cama bloqueada

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts
1. corrige tests del gestor de agendas
=> refactor para test gestor de agendas

cypress/e2e/apps/rup/ejecucion.spec.js
https://proyectos.andes.gob.ar/browse/RUP-318
1. Se hizo un cambio ya que fallaron unos test en la ultima corrida 
BUILD NUMBER: [6709](http://condorpiedra.andes.gob.ar:85/6709/mochawesome.html) CYPRESS RUN: [5562](https://dashboard.cypress.io/projects/xr7gft/runs/5562/specs)
=> RUP -  Cambia detalle en wait

cypress/e2e/apps/rup/internacion/medica/registros.spec.ts, cypress/plugins/seed-internacion.js
1. Corrige configuracion de cama en DB al crear estados con paciente
=> IN - Fix registro de cama ocupada (medica/enfermeria 'registros')

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts
=> CITAS:  actualiza filtro fechas gestor agendas

cypress/e2e/apps/perinatal/listado-pacientes.spec.ts
Elimina comparacion por edad, ya que es fija y no se calcula en base a la fecha de nacimiento.
1. 
2. 
3.
=> fix(PER): quita control por edad en datos del listado

cypress/e2e/apps/solicitud/aceptarSolicitud.spec.js, cypress/e2e/apps/solicitud/anularSolicitud.spec.js, cypress/e2e/apps/solicitud/asignarSolicitud.spec.js, cypress/e2e/apps/solicitud/darTurnoSolicitud.spec.js, cypress/e2e/apps/solicitud/liberarTurnoSolicitud.spec.js, cypress/e2e/apps/solicitud/nuevaSolicitudEntrada.spec.js, cypress/e2e/apps/solicitud/nuevaSolicitudSalida.spec.js, cypress/e2e/apps/solicitud/referirSolicitud.spec.js, cypress/e2e/apps/solicitud/responderSolicitud.spec.js, cypress/e2e/apps/solicitud/solicitudes.spec.js
1.  Se corrigieron todos los test con los nuevos componentes que se agregaron en el refactor del modulo de solicitudes.
2. 
3.
=> TOP - Ediciion de los test en el modulo de solicitud

cypress/e2e/apps/gestor-usuarios/perfiles.spec.js, cypress/e2e/apps/gestor-usuarios/usuarios.spec.js
https://proyectos.andes.gob.ar/browse/GDU-51
https://proyectos.andes.gob.ar/browse/GDU-52
https://proyectos.andes.gob.ar/browse/GDU-54
1. Se corrigen errores en el test de usuarios y perfiles.
=> CITAS - Agregar filtro en listado de perfiles

cypress/e2e/apps/gestor-usuarios/perfiles.spec.js, cypress/e2e/apps/rup/internacion/estadistica/egresos.spec.ts, cypress/e2e/apps/visualizacion-informacion/bi-queries.spec.js
1. Se fixean casos en el gestor, egreso en capa estadistica y bi-queries
=> Fix - Casos de tests no detectados en ultimos merges

cypress/e2e/apps/rup/colonoscopia.spec.ts, cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/e2e/apps/rup/punto-inicio/punto-inicio-sidebar.spec.ts, cypress/e2e/core/mpi/mpi-registro-con-dni.spec.ts, cypress/support/index.d.ts
1. Seteo de de intercepciones para que no devuelvan resultados cacheados
2. Actualización de comandos deprecados y extensiones de archivos
3. Eliminación de cogo comentado
=> Actualizaciones varias

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts
=> Fix en gestor de agendas

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts
=> adaptacion para funcionalidad de app

cypress/e2e/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
https://proyectos.andes.gob.ar/browse/MISC-266
1.  Se cambio el label de Documento por Paciente
=> MISC - label de paciente por documento

cypress/e2e/apps/citas/turnos/dar_turno.spec.js, cypress/e2e/apps/citas/turnos/punto_inicio.spec.ts, cypress/e2e/apps/perinatal/listado-pacientes.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts, cypress/e2e/core/tm/profesional/profesional.spec.ts
https://proyectos.andes.gob.ar/browse/MISC-226
1. Se actualizan funciones/operadores cypress deprecados y se adecua algun response a los cambios de la funcionalidad.
=> MISC - Agregar alias y documento extranjero a datos de paciente

cypress/fixtures/agenda-auditada-con-paciente.json, cypress/fixtures/agenda-auditada.json
https://proyectos.andes.gob.ar/browse/CIT-189
1.  Se agrega un atributo auditable: true en la linea 38
=> CIT - agendas auditadas

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.js, cypress/e2e/apps/epidemiologia/inscripcion-profesionales.spec.ts, cypress/e2e/apps/epidemiologia/seguimiento/seguimiento.spec.ts, cypress/e2e/apps/solicitud/darTurnoSolicitud.spec.js, data/authUsers/authUsers_basic.json
https://proyectos.andes.gob.ar/browse/CIT-221
1. Se edita el test 'clonar agenda con una institucion asignada' eliminando lo de agenda dinámica. Y en su lugar se crea una agenda que no es dinámica. Ya que  la tarea justamente se trata de no clonar agendas dinámicas. 
2. Se agrega el test 'intentar clonar agenda dinamica con institucion asignada' para comprobar que al ser una agenda dinámica no encuentre el botón 'Clonar agenda'. Y se incluye la institución asignada para que sea más completo el test.
=> CITAS - No clonar agendas dinamicas 

cypress/e2e/apps/com/com.spec.ts, cypress/e2e/core/auth/login.spec.ts, cypress/e2e/core/auth/select-organizacion.spec.js
https://proyectos.andes.gob.ar/browse/MISC-267
1. Se adaptan request de organizaciones segun cambios en app
=>  MISC - Visualización de solo efectores activos en el LogIn Andes

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.js
https://proyectos.andes.gob.ar/browse/CIT-208
1. Se cambia plexButton por plexButtonIcon en ambos componentes, 
2. Para pasar  cambios del PR: https://github.com/andes/app/pull/2862
=> (refactor)CIT - Aplicar mockup en clonar agendas

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, data/conceptoTurneable/conceptoTurneable_basic.json
https://proyectos.andes.gob.ar/browse/CIT-217
1.  Se agrega verificacion en caso de que no exista el plex-bool de Agenda Dinamica
2.  Test para pasar el PR: https://github.com/andes/app/pull/2856
=> (feat)CIT - Configurar agenda dinamica por concepto turneable

cypress/e2e/apps/visualizacion-informacion/bi-queries.spec.js
1. Quita required de query, segun nuevos criterios.
=> BI - Permisos por zona

cypress/e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/ingresos.spec.ts, cypress/e2e/apps/rup/punto-inicio/punto-inicio-sidebar.spec.ts, cypress/support/mapa-camas.js
Correccion de casos de test según últimos cambios
=> IN - Deshacer internación

cypress/e2e/apps/visualizacion-informacion/bi-queries.spec.js
Cambia el filtro de organización en queries 
1. 
2. 
3.
=> fix(QUERIES): corrige filtro en visualizacion de informacion

cypress/e2e/apps/perinatal/control-alertas.spec.ts, cypress/e2e/core/mpi/mpi-registro-bebe.spec.ts, cypress/support/index.d.ts, cypress/support/plex.js
Se corrigen test
1. Se agrega comando plexHelp
2. Se actualizan test en alerta perinatal
3. Se actualizan test de paciente-bebe
=> Se corrigen test varios

cypress/support/mapa-camas.js
https://proyectos.andes.gob.ar/browse/IN-532
https://github.com/andes/app/pull/2853
1. Modificada leyenda al "deshacer internación"
=> IN -  Control anular internación

cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.ts, cypress/e2e/core/mpi/mpi-registro-bebe.spec.ts, cypress/e2e/core/mpi/mpi-registro-sin-dni.spec.ts
Fix de casos de registro de pacientes que agregan una nota
=> fix(mpi): error agregando nota

cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts
https://proyectos.andes.gob.ar/browse/IN-567
1. Cambiar de label "Médico" por "Profesional a cargo"
=> IN - Cambiar nombre al seleccionar perfil

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.ts, cypress/e2e/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js, cypress/e2e/apps/epidemiologia/seguimiento/seguimiento.spec.ts, cypress/e2e/apps/solicitud/darTurnoSolicitud.spec.js, cypress/e2e/monitoreo/conceptos_turneables.spec.js, cypress/fixtures/agenda-auditada-con-paciente.json, cypress/fixtures/agenda-auditada.json, data/authUsers/authUsers_basic.json, data/profesional/profesional_basic.json
https://proyectos.andes.gob.ar/browse/CIT-220
1. Se corrige test de la rama CIT-169, https://github.com/andes/app/pull/2732.
2. Se agregan nuevos usuarios en authUsers_basic.json que no estaban agregados.
3. Se cambia el plexSelect de label="Equipo de Salud" a name="modelo.profesionales", porque fue cambiado en la app.
=> CITAS - Actualizar test CITAS para PR

cypress/support/plex.js
1. Se modifican comandos de plex-select para reparar casos de test
- [] Si
=> PLEX - Repara casos de test para plex-select

cypress/e2e/apps/citas/turnos/punto_inicio.spec.ts, cypress/e2e/core/mpi/busqueda.spec.ts
https://proyectos.andes.gob.ar/browse/PLEX-324
1. 
2. 
3.
=> plex-icon se corrigen test por actualización de íconos

cypress/e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/egresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/movimientos.spec.ts
Ajuste segun pr https://github.com/andes/app/pull/2926
1. Se adaptan test de egreso y movimientos de internacion
=> INT - Refactor en controles de ingreso y egreso

cypress/e2e/apps/citas/turnos/punto_inicio.spec.ts
https://proyectos.andes.gob.ar/browse/CIT-214
1. Crea reglas para nuevo selector en punto_inicio.specs
2. 
3.
=> CIT - Implementa selector de financiadores

cypress/e2e/apps/epidemiologia/inscripcion-profesionales.spec.ts
https://proyectos.andes.gob.ar/browse/MAT-151
1. Se corrigió test: Crear usuario para profesional.
=> MAT - Pantalla creacion usuario

cypress/support/mapa-camas.js
https://proyectos.andes.gob.ar/browse/IN-281
1.  En mapa-camas.js se agrega el campo 'cda:*' en los permisos del usuario de prueba
=> IN - Agrega permisos de CDA para internación

cypress/e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica/egresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/egresos.spec.ts, cypress/e2e/apps/rup/internacion/medica/movimientos.spec.ts
https://proyectos.andes.gob.ar/browse/IN-557
1.  Se corrigieron los test donde se egresa un paciente de internacion
=> IN - Mejoras en egreso internacion

cypress/e2e/apps/epidemiologia/seguimiento/seguimiento.spec.ts, data/profesional/profesional_basic.json
1. Corrige tests de seguimiento epidem. y listado perinatal segun modificaciones en app y api.
=> CIT - Crear agenda con profesional habilitado

cypress/e2e/apps/huds/huds.spec.ts, cypress/e2e/apps/rup/ejecucion/agregar-conceptos.spec.ts, cypress/support/rup.js
https://proyectos.andes.gob.ar/browse/RUP-357
1.  Nuevo test 'Editar paciente desde HUDS' en huds.spec
=> HUDS - Editar paciente desde HUDS

cypress/e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts
https://proyectos.andes.gob.ar/browse/IN-553
1. Se corrigieron los test de egreso en capa unificada
=> IN - Mejorar consulta para listado médico

cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts
https://proyectos.andes.gob.ar/browse/IN-579
1. Corrige casos para recuperación de historial con botón de búsqueda
=> IN - Incorporar botón de búsqueda en historial

cypress/e2e/apps/solicitud/acciones-solicitud.spec.ts, cypress/e2e/apps/solicitud/nuevaSolicitudSalida.spec.ts, cypress/e2e/apps/solicitud/solicitudes.spec.ts
https://proyectos.andes.gob.ar/browse/TOP-153
1. En solicitudes de entrada, se elimina el badge de "contrarreferida".
=> TOP - Eliminar contrarreferida

cypress/e2e/apps/citas/turnos/punto_inicio.spec.ts, cypress/e2e/apps/puco/puco.spec.js
1. Corrige casos para financiadores con versiones no válidas
=> MPI: Condición trimestral para devolución de obra social de un paciente

cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.ts, cypress/e2e/apps/epidemiologia/ficha-epidemiologica.spec.ts, cypress/e2e/apps/epidemiologia/seguimiento/seguimiento.spec.ts, cypress/e2e/apps/huds/huds.spec.ts, cypress/e2e/apps/mobile/mobile-profesional.spec.ts, cypress/e2e/apps/rup/colonoscopia.spec.ts, cypress/e2e/apps/rup/ejecucion.spec.js, cypress/e2e/apps/rup/ejecucion/agregar-conceptos.spec.ts, cypress/e2e/apps/rup/ejecucion/agregar-huds.spec.ts, cypress/e2e/apps/rup/elementos-rup/atomo-checklist.spec.ts, cypress/e2e/apps/rup/elementos-rup/atomo-select.spec.js, cypress/e2e/apps/rup/elementos-rup/atomo-select.spec.ts, cypress/e2e/apps/rup/elementos-rup/elemtos-rup-requeridos.spec.ts, cypress/e2e/apps/rup/elementos-rup/reglas-dinamicas.spec.ts, cypress/e2e/apps/rup/elementos-rup/repetir-registro.spec.ts, cypress/e2e/apps/rup/elementos-rup/seccionado.spec.js, cypress/e2e/apps/rup/internacion/epicrisis.spec.ts, cypress/e2e/apps/rup/internacion/medica/registros.spec.ts, cypress/e2e/apps/rup/nino-sano.spec.ts, cypress/e2e/apps/rup/odontograma/odontograma.spec.ts, cypress/support/rup.js
https://proyectos.andes.gob.ar/secure/Dashboard.jspa
1.  Se corrigen y actualizan múltiples test correspondientes al modulo RUP.
=> RUP- Corregir TEST del modulo RUP

cypress/e2e/apps/auditoria/auditoria.spec.ts, cypress/e2e/apps/citas/turnos/dar_turno.spec.ts, cypress/e2e/apps/rup/internacion/estadistica-v2/egresos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica-v2/ingresos.spec.ts, cypress/support/mapa-camas.js
https://proyectos.andes.gob.ar/browse/IN-552
1. 
2. 
3.
=> IN - Internación sin movimiento de ingreso

cypress/plugins/seed-agenda.js
https://proyectos.andes.gob.ar/browse/CIT-228
1. Se modifica el seed de crear agendas para que las agendas dinámicas no tengan turnos.
=> CIT - Ventanilla: poder dar turno con llave

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, cypress/e2e/apps/rup/punto-inicio/punto-inicio-sidebar.spec.ts
Revisión de casos de test que no estaban pasando
1. Modificaciónes en general.
=> fix(MISC): Ajustes en casos de CITAS (gestor) y RUP

cypress/support/mapa-camas.js
1. Reemplaza busqueda de dropdown por button
=> IN (Fix) - Deshacer internación

cypress/e2e/apps/solicitud/solicitudes.spec.ts
https://proyectos.andes.gob.ar/browse/TES-49
1.  Actualización de los tests tras modificaciones en pantallas de creación de reglas de entrada en solicitudes TOP.
=> TOP - Actualiza tests para nuevas reglas de entrada

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts
https://proyectos.andes.gob.ar/browse/CIT-210
1.  Se modificó test gestor_agenda.spec.ts de acuerdo al nuevo mockup.
2.  Test: suspender agenda disponible con turno y reasignarlo.
3.  Test: suspender turno de agenda publicada.
=> (CIT-210) Nuevo mockup Reasignación de turnos

cypress/e2e/apps/rup/internacion/medica/registros.spec.ts
https://proyectos.andes.gob.ar/browse/PRIV-70
1. 
2. 
3.
=> PRIV - Agregar campo observación en motivos

cypress/e2e/apps/mobile/mobile-paciente.spec.ts, cypress/e2e/apps/mobile/mobile-profesional.spec.ts
Se corrige ruta de acceso a login,ya que con las nuevas pantallas se separan el login de pacientes y el de profesionales
=> fix(AM): corrige rutas de acceso para mobile

cypress/e2e/apps/rup/internacion/medica/registros.spec.ts
1. Modifica acceso al motivo observando registros de cama medica y enfermeria
=> HUDS (Fix) - Control de motivo de acceso 

cypress/e2e/apps/citas/turnos/punto_inicio.spec.ts
=> CIT - Fix liberar turno

cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.ts, cypress/e2e/apps/rup/colonoscopia.spec.ts, cypress/e2e/apps/rup/ejecucion.spec.js, cypress/e2e/apps/rup/punto-inicio/punto-inicio-listado.spec.ts, cypress/e2e/apps/rup/punto-inicio/punto-inicio-navegacion.spec.js, cypress/e2e/apps/rup/punto-inicio/punto-inicio-sidebar.spec.ts, cypress/e2e/apps/solicitud/nuevaSolicitudEntrada.spec.ts
https://proyectos.andes.gob.ar/browse/RUP-370
1.  Se corrigen test para adaptar la UI de la nueva implementación de RUP
=> RUP - Implementa mockups en punto de inicio

cypress/e2e/apps/rup/internacion/estadistica/ingresos.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/periodos-censables.spec.ts
https://proyectos.andes.gob.ar/browse/IN-594
1. Implementa casos de test al agregar y eliminar periodos censables
=> IN - Implementa periodos censables en internacion

cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.ts
Se corrige test en planificación agendas no-nominalizas
1. cambia tooltip por icon para iniciar prestación en RUP
2. se quita función "only"
3.
=> CITAS: fix en test planificacion agendas no-nominalizas

cypress/e2e/apps/huds/huds.spec.ts, cypress/e2e/apps/rup/ejecucion.spec.js, cypress/e2e/apps/rup/ejecucion/agregar-huds.spec.ts, cypress/support/rup.js
https://proyectos.andes.gob.ar/browse/HUDS-74
1. Se corrigen tests para casos con nuevos elementos de HUDS
=> HUDS - Modifica tests para nuevos casos

cypress/e2e/apps/rup/colonoscopia.spec.ts, cypress/e2e/apps/rup/ejecucion.spec.js, cypress/e2e/apps/rup/internacion/epicrisis.spec.ts, cypress/e2e/apps/rup/internacion/medica/registros.spec.ts, cypress/e2e/apps/rup/punto-inicio/punto-inicio-sidebar.spec.ts, cypress/e2e/apps/visualizacion-informacion/exportar-huds.spec.ts, cypress/fixtures/huds/modalHuds.json
https://proyectos.andes.gob.ar/browse/PRIV-65
https://github.com/andes/app/pull/2958 
Se agrega intercept cada vez que se llama al servicio que trae el/los motivos Huds cuando:
1.  Se inicia una prestación desde cualquier módulo
2.  Se accede explicitamente a la HUDS
3.  Se continua una prestación
4.  Se accede a plan de indicaciones
=> PRIV-  Visualizar motivos de acceso a la HUDS

cypress/e2e/apps/solicitud/nuevaSolicitudEntrada.spec.ts
https://proyectos.andes.gob.ar/browse/GDU-64
1. Se agrego un nuevo botón de confirmar.
2. Se modifico el plexSelect para que lograra seleccionar al profesional.
=> GDU - Controlar datos del profesional asociado al usuario

cypress/e2e/apps/citas/agendas/gestor_agenda.spec.ts, cypress/e2e/apps/citas/turnos/dar_turno.spec.ts, cypress/e2e/apps/citas/turnos/punto_inicio.spec.ts, cypress/e2e/apps/gestor-usuarios/perfiles.spec.js, cypress/e2e/apps/solicitud/turnos.spec.ts, cypress/plugins/seed-agenda.js, cypress/support/commands.js, cypress/support/gestorUsuario.js
Test desactualizados hace tiempo.
1. Se corrigen varios casos de test desactualizados
=> MISC - Fix de casos de test en general

cypress/e2e/apps/citas/agendas/planificacion_agendas.spec.ts, cypress/e2e/apps/rup/ejecucion.spec.js, cypress/e2e/apps/rup/nino-sano.spec.ts, cypress/e2e/apps/solicitud/nuevaSolicitudEntrada.spec.ts
Fix test varios
1. Se agrega intercept para request snomed.
2. Se modifica botón de "confirm" de modal que no aparece en bandeja de entrada top.
3. wait en algunos test que no alcanzan a actualizarse
4.
=> fix: se corrigen errores en test varios

cypress/e2e/apps/gestor-usuarios/usuarios.spec.js, cypress/e2e/apps/rup/internacion/medica/registros.spec.ts, cypress/e2e/core/auth/select-organizacion.spec.ts, cypress/e2e/core/tm/organizacion/organizacion.spec.ts, data/authUsers/authUsers_basic.json
=> Fixea text varios

cypress/e2e/apps/rup/ejecucion/agregar-conceptos.spec.ts, cypress/e2e/apps/rup/internacion/estadistica/egresos.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/detalle-cama.spec.ts, cypress/e2e/apps/rup/internacion/mapa-camas/periodos-censables.spec.ts, cypress/e2e/apps/rup/internacion/medica/egresos.spec.ts, cypress/e2e/apps/rup/nino-sano.spec.ts
https://proyectos.andes.gob.ar/browse/IN-593
1. modifica edicion de egreso en capa estadistica
=> IN (Fix) - Duplicación de egresos y otros
