andes/andes-test-integracion

cypress/integration/core/mpi/mpi.spec.js

Caso de test habilitación y deshablitación de botón validar renaper.
[Ref. a issue en app #1234](https://github.com/andes/app/issues/1234)
Issue resuelto branches:
- API: [v4.5.0](https://github.com/andes/app/pull/1171)
- APP: [fixesMpi](https://github.com/andes/app/pull/1172)

caso de test habilitación y deshablitación de boton validar renaper

---

cypress/integration/apps/puco/puco.spec.js

Es una prueba simple donde se verifica que al buscar una persona en puco se haga la llamada correcta al endpoint de la api, se intercepta y hardcodea la respuesta

PUCO - Interceptar llamada a la API

---

cypress/integration/apps/gestor-usuarios/perfiles.spec.js

Casos de Test: se crea un nuevo perfil y se edita el estado de los perfiles de usuarios.
1. Agregar permisos de un perfil existente.
2. Inactivar un perfil activo y verificar que se vea desactivado.
- [] Si

Perfiles de usuarios - alta y modificación con perfiles

---

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
package.json

Agrega tests para suspensión de turnos y agendas
1. Se sumó test para suspender agenda disponible sin turnos asignados y verificar estado
2. Se sumó test para suspender agenda publicada con turnos asignados y verificar estado
3. Se sumó test para suspender agenda publicada con un turno asignado y reasignar el turno que tiene a otra agenda
4. Se sumó un test para suspender turno de agenda planificada

CITAS: sumados tests para suspensión de agendas y turnos de agendas

---

cypress/integration/apps/rup/ejecucion.spec.js

- Actualizar tests porque fallan
1. Cambios para funcionar con conceptos snomed/snowstorm
2. Se actualiza código para que use métodos de plex
3. Se quitan múltiples wait() 
- [] Si

refactor(RUP): Iniciar prestaciones fuera agenda, turno y sobreturno

---

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js

1. Se borran las lineas que cancelaban el cartel de ayuda al crear una agenda dinámica.
- [] Si
Observación: Requiere actualización el la App que elimina el cartel de ayuda.

AGENDAS: Elimina swal('cancel') al crear agendas

---

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js

Agregar controles a la API para comprobaciones más profundas, con `expect()`, `route` y `wait` en Cypress
1. Se agregaron controles al momento de agregar diagnósticos, entre otros.
- [] Si

feature(revisionAgendas): se agregan controles de API

---

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
cypress/integration/apps/citas/agendas/gestor_agendas_listado.spec.js
cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js

**TEST EN JENKINS #175**
Agregar control de datos que devuelve el **expect(xhr.response.body)** para verificar que los datos son correctos 
**GESTOR DE AGENDAS**
1. Control de datos en "Editar agenda publicada"
2. Control de datos en "Editar agenda en planificación"
3. Control de datos en "Suspender agenda disponible sin turnos"
4. Control de datos en "Suspender agenda disponible con turnos"
5. Control de datos en "Suspender agenda disponible con turno y reasignarlo"
6. Control de datos en "Suspender turno de agenda publicada"
**GESTOR DE AGENDAS - LISTADO**
1. Control de datos en "visualizar agendas de ayer y hoy"
2. Control de datos en "visualizar agendas de hoy y mañana"
3. Control de datos en "visualizar agendas del día y por tipo de prestación"
4. Control de datos en "visualizar …

CITAS: Control de datos en test de agendas

---

cypress/integration/apps/citas/turnos/dar_turno.spec.js

1.  Se crea test para confirmar que al momento de hacer click en al boton 'NO SE ASIGNA TURNO' se guarde la organizacion 
- [] Si

Dar Turno: test para rechazo de turno

---

cypress/integration/apps/solicitud/solicitudes.spec.js
cypress/plugins/seed-agenda.js

Al correr los Pull Requests https://github.com/andes/app/pull/1531 y https://github.com/andes/api/pull/886 en jenkins no pasaba test de "dar turno autocitado"
1. Se cambio la forma en que se crea agenda con turnos reservados para profesional
2. Se agrego en seed para que se puedan crear dichas agendas para profesional
3. Se agregaron diferentes controles de espera para que no falle el test

fix(TOP): arreglo test de dar turno autocitado

---

cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js

Falla el test **Guardar, clonar y verificar botón iniciar prestación en agenda no nominalizada** cuando corre en modo consola (Jenkins). Notar que en modo gráfico (browser) corre sin problemas.
1. Se actualizó la manera en que se usan las fechas con moment

fix(clonar-agenda): se mejora configuración de fechas

---

cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js

Controlar historial en BD y que se cambie el badge cuando se asigna un profesional a la solicitud
1. Se sumó un test que crea una solicitud, la asigna a un profesional y luego verifica que se vea listada en la pantalla 'Mis solicitudes'
2. Verifica que el movimiento se asignación se guarde en el historial de la solicitud

TOP: nuevo test para solicitudes asignadas

---

cypress/integration/apps/rup/colonoscopia.spec.js
cypress/integration/apps/rup/ejecucion.spec.js
cypress/integration/apps/rup/nino-sano.spec.js
cypress/integration/apps/rup/odontograma/odontograma.spec.js
cypress/integration/apps/solicitud/solicitudes.spec.js

1. Se quitó un click en un botón que ya no existe (seleccionar paciente) al crear una Prestación Fuera de Agenda, ya que ahora simplemente aparece el campo de búsqueda directamente.
~~cy.plexButton('SELECCIONAR PACIENTE').click();~~

fix(fuera-agenda-rup): se quita click en botón seleccionar paciente

---

cypress/fixtures/nota-privada.json
cypress/integration/apps/rup/ejecucion.spec.js

Controlar que cuando se carga una nota privada en una prestacion, en la huds, el profesional que la registró la pueda ver y otros usuarios no.
1. Se agrega test de nota privada
2. Se agrega fixture nota-privada
- [] Si
La funcionalidad para que el profesional pueda ver la nota privada que registro todavia no esta en master, al momento de mergear ese fix se debe completar el test.

RUP: Test nota privada

---

cypress/integration/apps/pantallas/pantallas.spec.js

Se agregar casos de tests para el gestor de pantallas
1. Test para crear/editar/eliminar pantalla de tipo turnero
2. Test para crear/editar/eliminar pantalla de tipo totem

PANTALLAS: nuevos tests para gestionar pantallas

---

cypress/integration/monitoreo/buscador-snomed.spec.js
cypress/support/plex.js

Desarrollo de tests para el buscador de SNOMED en Monitoreo
1. Test para la búsqueda de un concepto por term y verificar que no existe
2. Test para la búsqueda de un concepto por term y verificar que existe
3. Nuevos comandos plexLabel y plexBadge

MONITOREO: sumados tests de buscador de snomed y nuevos comandos 

---

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js

Fix para tes de suspensión de turno de una agenda publicada
1. Se crea agenda con un profesional asignado y se realizan las modificaciones en el test _suspender turno de agenda publicada_ .
- [] Si

CITAS: suspender turno publicada

---

docker/docker-compose.yml

Remueve la conexión a la base de datos MPI
1. Modificación en docker-compose
2. 
3.

chore(docker): quita la base de mpi

---

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
cypress/integration/apps/citas/turnos/dar_turno.spec.js
cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js
cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js
cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js
cypress/plugins/seed-agenda.js

Modificar la forma en la que se le asigna la hora inicio y fin a las agendas al crearlas para que no haya conflictos según el horario en el que se corren los test.
1. En seed-agenda, se modifica la forma en que se toman los parámetros. Ingresa una hora fija y no el offset para sumarle a la hora actual.
2. Se modifican todos los test que usaban seed-agenda para que funcionen correctamente con el nuevo formato.
- [] Si

Agenda: Modificacion en seed-agenda

---

cypress/integration/apps/citas/agendas/gestor_agenda.spec.js

Test para verificar que se refleje el cambio de estado de una agenda suspendida
1. Se agrega test que verifica que cuando una agenda se suspende, muestre correctamente los datos
- [] Si
Debe correrse en https://github.com/andes/app/pull/1540

CITAS: actualizacion de estado de agenda

---

cypress/plugins/seed-prestaciones.js

El en seed de prestación, el `id` de profesional de solicitud (`prestacion.solicitud.profesional.id`), actualmente se está guardando como `_id`. Esto repercute en que las prestaciones generadas desde el seed no pueden ser encontradas por la API al ser filtradas por idProfesional.
1. Arregla id de profesional de solicitud en seed de prestación
- [] Si

Fix: Arregla id de profesional de solicitud en seed de prestación

---

cypress/integration/apps/citas/agendas/revision-agenda/revision_agendas_con_paciente.spec.js

El nuevo plex-content no permite scrollTo debido a una clase de CSS:

fix(agenda): remove scrollto

---

cypress/integration/apps/citas/turnos/punto_inicio.spec.js

Modificar el campo celular en el caso de la activación de la app mobile por plex-phone dado cambio en la app.
1. En test de activacion de app mobile, se modifica el campo celular.
- [] Si

MPI: se cambia plexText por plexPhone

---

cypress/integration/apps/citas/turnos/punto_inicio.spec.js
cypress/integration/apps/rup/ejecucion.spec.js
cypress/integration/apps/rup/nino-sano.spec.js

Modificar test para funcionar correctamente con el nuevo cambio en obras sociales
1. Se eliminaron las llamadas a los get de obra social
- [] Si
Debe correrse en las ramas https://github.com/andes/api/pull/1010 y https://github.com/andes/app/pull/1752

Obra-Social: Elimina llamado a getObraSocial

---

cypress/integration/apps/rup/punto-inicio/punto-inicio-listado.spec.js

Se corrige tests que fallaba con https://github.com/andes/app/pull/1873
1. Se agrega un control por nombre de profesional en test _'no visualiza agendas de otros profesionales'_

RUP: arreglo de tests para rama RUP-165

---

cypress/integration/apps/com/com.spec.js

Solucionar los errores en los tests de com 
1. Se acortan los textos en descripción
2. Se elimina un wait de disclaimer

COM: arreglo de errores en tests 

---

cypress/integration/apps/com/com.spec.js

Acomodar tests de COM para https://github.com/andes/app/pull/1986
1. Al crear una nueva derivación, se limpia el profesional seteado por defecto

COM: arreglo de tests de COM

---

cypress/fixtures/solicitudes/solicitud-pendiente.json
cypress/integration/apps/solicitud/anularSolicitud.spec.js

corregir error en test de anulación
1. El test de anulación tomaba una solicitud pendiente que tenía movimientos en el historial. 
2. Con el cambio en la app no se pueden anular solicitudes con movimientos en el historial.
3. se agrega fixture de solicitud pendiente

fix(anular-solicitud): para que tome los cambios en la anulación

---

cypress/integration/apps/visualizacion-informacion/exportar-huds.spec.ts
cypress/support/index.d.ts
data/authUsers/authUsers_basic.json

https://proyectos.andes.gob.ar/browse/PRIV-61
1. Se agregan test para realizar la petición de exportar Huds de un paciente con los distintos filtros.
2. Se modifica  en `index.d.ts` la función `plexDateTime `para poder usar `skipEnter` y `clear`.
3. Se agrega permiso` huds:exportarHuds` en la colección `AuthUsers`

EXPORT-HUDS: Test para exportar huds

---

cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
cypress/plugins/seed-prestaciones.js

Tests para exportar prestaciones desde el buscador de turnos y prestaciones.
1. Se agregan dos test para el buscador de turnos y prestaciones.
2. Se agrega guardar una codificación cuando es una prestación fuera de agenda en el seed de prestaciones.

TURNOS-PRESTACIONES: Exportar prestaciones

---

cypress/plugins/seed-prestaciones.js

Fix para test del buscador de turnos y prestaciones.
1. Por un nuevo cambio en la búsqueda de las prestaciones fuera de agenda, se agrega el campo id a la organización para que funcionen correctamente los test del buscador.

SEED-PRESTACIONES: Agrego campo id organización

---

cypress/integration/apps/epidemiologia/ficha-epidemiologica.spec.ts

Fix para nuevo requerimiento de restricción de días entre dos fichas del mismo paciente
1. Se agrega modifica un test de ficha por el nuevo requerimiento que un paciente no puede tener dos fichas distintas en un rango de 14 días.

FICHA EPIDEMIOLÓGICA: check dias

---

cypress/integration/apps/epidemiologia/seguimiento/seguimiento.spec.js

El test de seguimiento falla. Esto se da porque no tenia en cuenta que las fichas confirmadas en otros test, crean seguimiento.
1. Se eliminan los controles de cantidad de seguimientos del get y se agrega un control por el paciente al que se le crea la ficha en este test.
2. Se elimina el wait.

Seguimiento: elimina control de cantidad y wait

---

cypress/integration/apps/perinatal/listado-pacientes.spec.ts
cypress/integration/apps/vacunacion/listado-vacunacion.spec.ts

Cambio de mensaje de éxito al guardar una nota
1. Se modifica el mensaje esperado al guardar un nota en el listado de vacunación

MISC: cambio de mensaje en toasts 

---

cypress/integration/apps/perinatal/control-alertas.spec.ts
cypress/integration/apps/perinatal/listado-pacientes.spec.ts

https://proyectos.andes.gob.ar/browse/PER-67
1. Se corrigió el filtro de "Agregar nota a paciente" ya que este mismo cuando se agrega o edita una nota el mensaje que muestra es el mismo para ambos casos cuando debería ser diferente.
2. Se agregaron los filtros "fecha de cita" y "ultimo control" ya que anteriormente no se podían por un problema en las cargas de las fechas.
3. En control-alertas se corrigió el ultimo filtro para controlar que el carnet del paciente no este vencido.

PER - corrección de filtros en modulo perinatal

---

cypress/e2e/apps/huds/huds.spec.ts

https://proyectos.andes.gob.ar/browse/RUP-387
1. Modifica test en selector de filtros de internación en prestación abierta de RUP

RUP - Modifica test para filtros en RUP
